### ISSUE TITLE
不支持SM2的秘钥交换算法

### ISSUE THREAD

**Issue by Retouch001** [muzipiao/GMObjC#1]
不知兄台是否有增加SM2的秘钥交换算法的实现的计划呢？

**Comment by muzipiao** [comment]
已增加 ECDH。

**Comment by JimAndLulu** [comment]
> 不知兄台是否有增加SM2的秘钥交换算法的实现的计划呢？

您好！请问 SM2的密钥交换算法是怎么实现的？
