### ISSUE TITLE
到EC_KEY_set_group(key, group)出现崩溃

### ISSUE THREAD

**Issue by zhaohailog** [muzipiao/GMObjC#101]
项目用到了一个加密的输入框三方库，导致在走到EC_KEY_set_group(key, group)出现崩溃，这个三方库在图中。三方库已经找不到更新的办法。只要去掉这个三方库，就正常了。
![企业微信截图_b8ef1277-17ff-4be7-a737-6cf6bec8ec3f](https://github.com/user-attachments/assets/9de9d0c7-4372-4b67-b0b3-004ef74fe466)
下面代码是出错的代码：
///MARK: - SM2 签名
+ (nullable NSString *)signData:(NSData *)plainData priKey:(NSString *)priKey userData:(nullable NSData *)userData{
    if (plainData.length == 0 || priKey.length == 0) {
        return nil;
    }
    
    if (userData.length == 0) {
        userData = [NSData dataWithBytes:SM2_DEFAULT_USERID length:strlen(SM2_DEFAULT_USERID)];
    }
    const char *private_key = priKey.UTF8String;
    uint8_t *plain_bytes = (uint8_t *)plainData.bytes;
    size_t plain_len = plainData.length;
    uint8_t *user_id = (uint8_t *)userData.bytes;
    size_t user_len = userData.length;
    
    ECDSA_SIG *sig = NULL;  // 签名结果
    const BIGNUM *sig_r = NULL;
    const BIGNUM *sig_s = NULL;
    const EVP_MD *digest = EVP_sm3();  // 摘要算法
    EC_GROUP *group = EC_GROUP_new_by_curve_name(kDefaultEllipticCurveType);
    BIGNUM *pri_num = NULL;  // 私钥
    EC_KEY *key = NULL; // 密钥对
    EC_POINT *pub_point = NULL; // 公钥坐标
    NSString *sigStr = nil;  // 签名结果
    do {
        if (!BN_hex2bn(&pri_num, private_key)) {
            break; // 私钥转 BIGNUM
        }
       
        key = EC_KEY_new();
        if (key==NULL){
            NSLog(@"EC_KEY_new 出错了!\n");
            
        }else{
//            NSLog(@"key是：%@",key);
        }
        
        if (group==NULL){
            NSLog(@"group 出错了!\n");
            
        }
        
        if (!EC_KEY_set_group(key, group)) {
            break;
        }
        if (!EC_KEY_set_private_key(key, pri_num)) {
            break; // 设置私钥
        }
        pub_point = EC_POINT_new(group);
        if (!EC_POINT_mul(group, pub_point, pri_num, NULL, NULL, NULL)) {
            break; // 私钥算出公钥
        }
        if (!EC_KEY_set_public_key(key, pub_point)) {
            break; // 设置公钥
        }
        // 计算签名
        sig = sm2_do_sign(key, digest, user_id, user_len, plain_bytes, plain_len);
        if (!sig) {
            break;
        }
        ECDSA_SIG_get0(sig, &sig_r, &sig_s);
        char *r_hex = BN_bn2hex(sig_r);
        char *s_hex = BN_bn2hex(sig_s);
        NSString *rStr = [NSString stringWithCString:r_hex encoding:NSUTF8StringEncoding];
        NSString *sStr = [NSString stringWithCString:s_hex encoding:NSUTF8StringEncoding];
        
        OPENSSL_free(r_hex);
        OPENSSL_free(s_hex);
        if (rStr.length == 0 || sStr.length == 0) {
            break;
        }
        // 如果转 Hex 不足 64 位前面补 0
        NSString *paddingR = [self bnToHexPadding:rStr];
        NSString *paddingS = [self bnToHexPadding:sStr];
        sigStr = [NSString stringWithFormat:@"%@%@", paddingR, paddingS];
    } while (NO);
    
    if (group != NULL) EC_GROUP_free(group);
    EC_POINT_free(pub_point);
    ECDSA_SIG_free(sig);
    EC_KEY_free(key);
    BN_free(pri_num);
    
    return sigStr;
}

**Comment by muzipiao** [comment]
1. 你用的估计是直接拖入GMObjC 源码的方式，这种方式要求项目 OpenSSL 版本是 1.1.1 的较高版本；
2. 出现上面的`group==NULL`，那是因为项目的 OpenSSL 版本太低，不包含 SM2 加密源码；
3. 要么把项目中的 OpenSSL 升级为 1.1.1 较高版本，例如`1.1.1w`；要想保留多个 OpenSSL，只有昨天说的2种方法。

OpenSSL 版本参考 [https://github.com/muzipiao/GMOpenSSL](https://github.com/muzipiao/GMOpenSSL)

**Comment by zhaohailog** [comment]
我想确认下，GMObjc依赖的OpenSSL是从哪里来的？因为我只有  pod 'GMObjC' ,'3.3.2'。没有专门处理OpenSSL。 还有你能帮我确定下，三方的OpenSSL在哪里？

**Comment by muzipiao** [comment]
手动编译的，源码地址 https://github.com/muzipiao/GMOpenSSL，编译脚本，选下面2个哪个都行，把 sm2.h sm3.h sm4.h 头文件添加到 header 就行

https://github.com/krzyzanowskim/OpenSSL.git
https://github.com/x2on/OpenSSL-for-iPhone.git

**Comment by zhaohailog** [comment]
我想着，我项目的三方既然支持sm2这类的国密加密，那我们这个加密的ssl用他们的ssl应该可以吧？如果可以的话，我怎么能将GMPenSSL（项目中)的删掉？  我想着能不用多个ssl就不用多个ssl

**Comment by muzipiao** [comment]
GMObjC 仅是对 OpenSSL 中的 SM2 的 Objective-C 封装，源码简单，将 GMObjC 源码拖入项目即可，看一下就明白。

项目中只要有 OpenSSL 的 1.1.1 以上较新版本即可，如`1.1.1q`。
