### ISSUE TITLE
pod install 3.0.0失败

### ISSUE THREAD

**Issue by zyh2123606** [muzipiao/GMObjC#102]
pod 3.0.0会报错，提示找不到这个分之了，怎么解决呀

**Comment by zyh2123606** [comment]
但是搭配GMOpenSSL "~>2.2.9"会报错Undefined symbol: nominal type descriptor for CoreGraphics.CGFloat

**Comment by muzipiao** [comment]
这应该是 Xcode 16 类型校验的错误，`CoreGraphics.CGFloat`和开源库应该关系不大

https://stackoverflow.com/questions/78999248/coregraphics-cgfloat-errors-after-updating-xcode-to-version-16

**Comment by zyh2123606** [comment]
好的，非常感谢
