### ISSUE TITLE
4.0迁移 问题

### ISSUE THREAD

**Issue by MLMzy666** [muzipiao/GMObjC#103]
关于SM4 CBC模式加解密， API变了，请问ivecData应该传什么值呢，以前和后台通讯是通的，现在您的API升级了，我们使用新的API后台无法解密，拜托了

**Comment by muzipiao** [comment]
猜测你是用`NSData *data = [@"Hex Key" dataUsingEncoding:NSUTF8StringEncoding];`直接转Data导致的。

1. ivec 是指初始化向量，可以看做一个随机数，用来增加密文的随机性，但加解密必须使用相同的 ivec；
2. 密钥，key 和 ivec 字符串都是 HEX 类型，Data 类型需要使用`dataFromHexString:`转为 Data；
3. 明文，要加密的明文一般不需要转 HEX，字符串可使用`dataUsingEncoding:`转为 Data；

```OC
// 如果需要传入 Data 类型，需要把 HEX 编码格式解码为 Data 类型，密钥 key 和 ivec 处理方式一样
NSData *ivecData = [GMSmUtils dataFromHexString:ivecHexString];
```

**Comment by MLMzy666** [comment]
感谢您的解答，多谢多谢。

在3.3.8中[GMSm4Utils ecbEncryptData:data key:sm4Key]；我可以，和我们的后台正常通讯

但是在新版本中，您的API出现了变化，增加了IV参数，因为后台发版本，涉及到多端的改动，所以想麻烦问问您，在3.3.8版本中，是不是默认了IV的值。如果有，我本地加上IV参数，就不用调后台了。

**Comment by muzipiao** [comment]
你要首先确认后端使用的时 ECB 还是 CBC模式加密，ECB 模式加密，不需要向量 IV 参数，CBC 加密才需要。

- **加密模式**: 
  - ECB (电子密码本模式): 将明文按照固定的块大小（16 字节）进行分割（不足补齐），逐个块加密。
  - CBC (密文分组链接模式): 每个明文块先与前一个密文块进行异或操作再加密，需要 16 字节的初始向量(IV)，安全性更高

**Comment by MLMzy666** [comment]
十分感谢您的解答，是我用错了API。原来3.3.8的工程用的是：
[GMSm4Utils ecbEncryptData:data key:sm4Key]，
对应4.0.1的ECB是：
[GMSm4Utils encryptDataWithECB:plainData keyData:[GMSmUtils dataFromHexString:sm4Key]];
是我用错了方法，用成了CBC。
已经解决了。
