### ISSUE TITLE
POD 导入后 导致百度地图直接无法初始化 

### ISSUE THREAD

**Issue by wangBlue** [muzipiao/GMObjC#11]
是不是里面的openssl和百度的openssl版本不同导致  编译也没问题  移除gmobjc 百度地图初始化成功。

**Comment by muzipiao** [comment]
估计是这个原因，原来一个 issue 也是反馈百度地图的问题，使用百度地图 SDK 后，导致加密结果为空，原因就是 OpenSSL 版本库问题。建议的解决办法：
方法1：使用最新版本的百度地图 SDK，新版本可能已升级了 OpenSSL，升级即可解决；
方法2.：OpenSSL 是 C 类型的库，方法重名时，会按照编译顺序，调用前面插入的方法；所以，如果你所集成的百度地图 SDK 里面 OpenSSL 的版本 >= 1.1.1 以上，在 Build Phases → Link Binary With Libraries 里面拖拽一下顺序，使百度地图 SDK 在前面，优先使用百度地图里面的 OpenSSL；若用 pod ，同样调整顺序，看看加密结果是否为空，就知道是不是1.1.1以上版本了，若是即可解决。

**Comment by wangBlue** [comment]
> 估计是这个原因，原来一个 issue 也是反馈百度地图的问题，使用百度地图 SDK 后，导致加密结果为空，原因就是 OpenSSL 版本库问题。建议的解决办法：
> 方法1：使用最新版本的百度地图 SDK，新版本可能已升级了 OpenSSL，升级即可解决；
> 方法2.：OpenSSL 是 C 类型的库，方法重名时，会按照编译顺序，调用前面插入的方法；所以，如果你所集成的百度地图 SDK 里面 OpenSSL 的版本 >= 1.1.1 以上，在 Build Phases → Link Binary With Libraries 里面拖拽一下顺序，使百度地图 SDK 在前面，优先使用百度地图里面的 OpenSSL；若用 pod ，同样调整顺序，看看加密结果是否为空，就知道是不是1.1.1以上版本了，若是即可解决。

感谢回复  我用的百度地图SDK5.2.0 应该就是很新的了，无法初始化  先升到最新5.3.0试试  
如果是库版本不对 我觉得也不应该初始化失败 纳闷

**Comment by NSLog-YuHaitao** [comment]
百度地图sdk5.3.0 app运行直接报Thread 1: EXC_BAD_ACCESS (code=257, address=0x6e) 怎么解决

**Comment by NSLog-YuHaitao** [comment]
@muzipiao 作者麻烦看一下

**Comment by wangBlue** [comment]
> 百度地图sdk5.3.0 app运行直接报Thread 1: EXC_BAD_ACCESS (code=257, address=0x6e) 怎么解

> 估计是这个原因，原来一个 issue 也是反馈百度地图的问题，使用百度地图 SDK 后，导致加密结果为空，原因就是 OpenSSL 版本库问题。建议的解决办法：
> 方法1：使用最新版本的百度地图 SDK，新版本可能已升级了 OpenSSL，升级即可解决；
> 方法2.：OpenSSL 是 C 类型的库，方法重名时，会按照编译顺序，调用前面插入的方法；所以，如果你所集成的百度地图 SDK 里面 OpenSSL 的版本 >= 1.1.1 以上，在 Build Phases → Link Binary With Libraries 里面拖拽一下顺序，使百度地图 SDK 在前面，优先使用百度地图里面的 OpenSSL；若用 pod ，同样调整顺序，看看加密结果是否为空，就知道是不是1.1.1以上版本了，若是即可解决。

百度那边我提工单了  他们openssl是 v1.0.2e

**Comment by NSLog-YuHaitao** [comment]
那最终如何解决?

**Comment by NSLog-YuHaitao** [comment]
你是怎么解决的这个问题

**Comment by NSLog-YuHaitao** [comment]
> > 百度地图sdk5.3.0 app运行直接报Thread 1: EXC_BAD_ACCESS (code=257, address=0x6e) 怎么解
> 
> > 估计是这个原因，原来一个 issue 也是反馈百度地图的问题，使用百度地图 SDK 后，导致加密结果为空，原因就是 OpenSSL 版本库问题。建议的解决办法：
> > 方法1：使用最新版本的百度地图 SDK，新版本可能已升级了 OpenSSL，升级即可解决；
> > 方法2.：OpenSSL 是 C 类型的库，方法重名时，会按照编译顺序，调用前面插入的方法；所以，如果你所集成的百度地图 SDK 里面 OpenSSL 的版本 >= 1.1.1 以上，在 Build Phases → Link Binary With Libraries 里面拖拽一下顺序，使百度地图 SDK 在前面，优先使用百度地图里面的 OpenSSL；若用 pod ，同样调整顺序，看看加密结果是否为空，就知道是不是1.1.1以上版本了，若是即可解决。
> 
> 百度那边我提工单了 他们openssl是 v1.0.2e

那你这个问题得到解决的办法了吗?

**Comment by LCBbest** [comment]
请问有解决办法吗 我也碰到这个问题了

**Comment by muzipiao** [comment]
是由于百度地图中 OpenSSL 和 GMObjC 依赖的 openssl.framework 版本不一致导致，cocoapods 不支持依赖同一个库的不同版本。
解决办法将 GMObjC 封装为 Framework，引入项目使用即可。
项目已支持 Carthage，如果 carthage update 失败，打开项目文件夹 GMObjCFramework 手动编译为 Framework 拖入项目即可（注意不需要再拖入 openssl.framework)

**Comment by wangBlue** [comment]
> 是由于百度地图中 OpenSSL 和 GMObjC 依赖的 openssl.framework 版本不一致导致，cocoapods 不支持依赖同一个库的不同版本。
> 解决办法：
> 不使用cocoapods集成百度地图，手动集成百度地图，将 GMObjC 封装为 Framework，引入项目使用即可。
> 项目已支持 Carthage，如果 carthage update 失败，打开项目文件夹 GMObjCFramework 手动编译为 Framework 拖入项目即可（注意不需要再拖入 openssl.framework)

按照作者的流程可以解决问题，我是百度地图用pods集成  手动编译了GMObjC 然后合并下模拟器和真机的库  测试没问题。
