### ISSUE TITLE
SM4 ECB 模式解密时程序崩溃

### ISSUE THREAD

**Issue by BingleiM** [muzipiao/GMObjC#13]
16 进制编码
密文 410cc52868d787be3374dc9d27e37e26dc26dc7d2653883d615b0d1dd707325e
秘钥 D4E06ACBEC6240E78802E5A910CD9589
调用 GMSm4Utils + (nullable NSString *)ecbDecryptText:(NSString *)ciphertext key:(NSString *)key; 函数解密时程序奔溃了
麻烦帮忙看下, 万分感谢

**Comment by muzipiao** [comment]
明文发一下，这个密文是怎么生成的，是后端传过来的吗？

**Comment by BingleiM** [comment]
明文是 75709c678eef32627bd1b312f433242cc4911bee88ea55ed8f61a1640f829102
后台使用秘钥加密的 D4E06ACBEC6240E78802E5A910CD9589, 使用的 SM4.ECB_No_Padding 模式加密生成的

**Comment by muzipiao** [comment]
后台肯定做了其他处理，与后台沟通采用的实际 padding 模式，GMSm4Utils 采用 pkcs7 补齐方式。
1. 首先是加密后长度，这个明文是 Hex 格式的，长度64 个字符，实际明文 char 类型字符串为 32 个，SM4 加密要求原文必须是 16 的倍数，无论采用 PKCS7 还是 PKCS5 补齐后长度都是 48 字符，加密后密文与原文长度相同为 48 字符，密文转为 Hex 格式为 96 字符格式，这里密文（410cc52868d787be3374dc9d27e37e26dc26dc7d2653883d615b0d1dd707325e）64字符长度肯定有问题；
2. 加解密对字符编码敏感，客户端采用 NSUTF8StringEncoding 格式，与后端核对；
3. 如果后端密文无法转为 NSString 格式，可以使用 NSData 格式进行加解密，或转为 Hex；
```objc
/// NSData 16 进制编码。返回值：16 进制编码的字符串
/// @param data 原数据（NSData 格式）
+ (nullable NSString *)dataToHex:(NSData *)data;

/// 16 进制字符串解码为 NSData。返回值：解码后的 NSData 对象
/// @param hexStr 16 编码进制字符串
+ (nullable NSData *)hexToData:(NSString *)hexStr;

+ (nullable NSData *)ecbEncryptData:(NSData *)plainData key:(NSString *)key;
+ (nullable NSData *)ecbDecryptData:(NSData *)cipherData key:(NSString *)key;
```
推荐你用这个 Mac 端工具与后端测试，加解密正常后使用GMSm4Utils 加解密也会正常。
[https://github.com/MxABC/DevDataTool](https://github.com/MxABC/DevDataTool)
