### ISSUE TITLE
接入百度地图，项目启动失败

### ISSUE THREAD

**Issue by LCBbest** [muzipiao/GMObjC#14]
接入百度地图的时候，百度地图加载失败，有什么解决方法吗

**Comment by muzipiao** [comment]
是由于百度地图中 OpenSSL 和 openssl.framework 版本不一致导致，解决办法将 GMObjC 封装为 Framework，引入项目使用即可。
项目已支持 Carthage，如果 carthage update 失败，打开项目文件夹 GMObjCFramework 手动编译为 Framework 拖入项目即可（注意不需要再拖入 openssl.framework)
