### ISSUE TITLE
最新版本打release包报错

### ISSUE THREAD

**Issue by doaspromised** [muzipiao/GMObjC#15]
Unable to determine target or target not included in OpenSSL build

**Comment by muzipiao** [comment]
这种应该是你集成有问题，GMObjC 依赖 openssl.framework，项目必须拖入引用 openssl.framework，且项目中不能有重复的 openssl。
重新集成或换种集成方式尝试。

**Comment by doaspromised** [comment]
依赖于GMOpenSSL  我把GMOpenSSL降到2.0.3版本就好了


| |
姜守栋
|
|
邮箱：18511632756@163.com
|

签名由 网易邮箱大师 定制

在2020年05月22日 18:17，CocoaFei 写道：

这种应该是你集成有问题，GMObjC 依赖 openssl.framework，项目必须拖入引用 openssl.framework，且项目中不能有重复的 openssl。
重新集成或换种集成方式尝试。

**Comment by muzipiao** [comment]
GMOpenSSL.framework 不同版本对应不同的架构，也可使用项目中脚本自行编译。
