### ISSUE TITLE
大佬 请教您一个问题

### ISSUE THREAD

**Issue by vindaTian** [muzipiao/GMObjC#16]
我看安卓那边C1C2C3中的C1 是65个字节 请问这个这个怎么解呀

**Comment by muzipiao** [comment]
C1 是椭圆曲线上的倍点，固定为 64 字节，转换为 Hex 进制为 128 字节。
Android 如果使用的是 Java 的 bouncycastle 库，那加密结果头部是 0x04，也就是说 C1 原文开头会多 1 个字节，转换为 Hex 进制后是 04 开头(04.....)，也就是多了2个字节（04），和其他库交互时，可根据实际情况增删 04 开头即可。

**Comment by vindaTian** [comment]
通透👍
