### ISSUE TITLE
sm4加密，密钥如何改成16位的？我们后台给了16位的密钥，无法加密。

### ISSUE THREAD

**Issue by MagiLi** [muzipiao/GMObjC#18]

**Comment by muzipiao** [comment]
16 字节秘钥如果不是 Hex 编码格式，调用 `NSString *keyHex = [GMUtils stringToHex:keyStr];` 转成 Hex 编码就是 32 字节秘钥了；若不是联系后端修改，OpenSSL 的 SM4_BLOCK_SIZE 固定是 16 位（Hex 编码格式为 32 位）。

**Comment by MagiLi** [comment]
多谢回复，现在已经可以加密了。
