### ISSUE TITLE
pod 完成就报错

### ISSUE THREAD

**Issue by hms040717007** [muzipiao/GMObjC#19]
<img width="1217" alt="截屏2020-06-09 10 12 24" src="https://user-images.githubusercontent.com/17900926/84098484-f9dba280-aa39-11ea-884d-a8527b0199b8.png">
pod集成后报错

**Comment by muzipiao** [comment]
应该是 pod 安装执行失败，尝试重新 `pod update --verbose` 安装试试。

**Comment by hms040717007** [comment]
在新项目就没事，在老项目就报错，不管pod集成还是拖进项目里面

**Comment by hms040717007** [comment]
是不是不支持armv7？

**Comment by muzipiao** [comment]
由于 armv7、 armv7s 大部分项目早已不再支持，GMObjC 依赖的静态库 GMOpenSSL 最新版本支持 x86_64 arm64 arm64e ，如果项目需要支持 armv7 系列，在 Podfile 里面添加一行 
`pod 'GMOpenSSL', '2.0.3'` 
指定固定版本即可，推荐项目移除 armv7和armv7s 。

GMOpenSSL 版本请查看 https://github.com/muzipiao/GMOpenSSL
