### ISSUE TITLE
for循环多次加密解密，会有一定几率出现解密失败的情况

### ISSUE THREAD

**Issue by JiangShoudong** [muzipiao/GMObjC#2]

**Comment by muzipiao** [comment]
单元测试中，使用for循环已进行过百万量级的测试，能否描述的详细一点：
1. 什么加解密，sm2还是sm4，什么模式的加解密；
2. 如果方便能否将测试代码贴出来，我查看测试一下。

**Comment by muzipiao** [comment]
已发现是由于 BIGNUM 转 Hex 个别情况下不足 64 位导致的加解密失败，原来的单元测试未包含此种测试所以未发现，已修复，谢谢提醒。
