### ISSUE TITLE
关于ECDHE的使用问题

### ISSUE THREAD

**Issue by lvzhao666** [muzipiao/GMObjC#20]
你好
我在使用ECDHE过程中遇到一个问题:
我们使用的椭圆曲线是:
```
基于 ECC NIST P-256 曲线(即 secp256r1)进行计算，该曲线的参数详情见:https://www.secg.org/SEC2-
Ver-1.0.pdf
  
"secp256r1": {
"p": 0xffffffff00000001000000000000000000000000ffffffffffffffffffffffff,
"a": 0xffffffff00000001000000000000000000000000fffffffffffffffffffffffc,
"b": 0x5ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b,
"g": (0x6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296,
0x4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5),
"n": 0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551,
"h": 0x1 }
```
我修改了您的代码
```
EC_GROUP *group = EC_GROUP_new_by_curve_name(NID_secp256k1); // 椭圆曲线
//我看着NID_secp256k1 很像 , 就替换了椭圆曲线, 
```
验证也是正确的.

但是我们有一个测试文档
```
    //A私钥85c888a8c5aaeba1f1a056a093ff874e3e01524f3571320680a13bdedab3db56
    //A公钥1c4ad6faf196e616c28832a540c78af8e0c3e4c6e27fcd82d479ae6497050db645c7debe0efc508e4f0d8a2fef5496c1174a4aa149e10cd5b2f02a5e7eb4faa6
    
    //B私钥1d9bec7294e2a7426acff1c48e69d2dc995d471d3fe045b1bc3fa21298813fc8
    //B公钥8d413fedaa2d0fd1036c27a3cc08e1776b951918513bbd5d8d22286ade63cfbccc4ae4bfcf69efb580409c056850429bbb6453227aa0fc0670c0f23c53593bee
    
    //结果
//59e7866e936b8f4f4bcca03fe7de81483ae78f9939cd8084a3bdca6f813dfd63762892918be716e7a169c717eb9dc3a92d777a47f2dcc620c0130f2906a18ac6
```
我现在把这个数据传到API里面,
计算秘钥的时候
int ret = ECDH_compute_key(ecdh_text, outlen, pub_point, key, 0);
ret = 0;
 
[我这边给的ECDHE文档.zip](https://github.com/muzipiao/GMObjC/files/4894463/ECDHE.zip)
结合我这边的数据, 在demo里面计算秘钥失败. 
能帮忙看下是什么原因吗?  
如果可以, 希望能得到您的帮助.

**Comment by muzipiao** [comment]
这里的公私钥不能用于加解密，说明密钥对无法使用，ECDH 当然无法协商出密钥，先测试密钥对能否使用。
看了你上传的文档，里面除了使用椭圆曲线外，还有 AES 加解密的操作，并不是单一密钥协商流程，给的测试数据无法使用。

**Comment by lvzhao666** [comment]
你好, 我的理解是这样的
双方先进行ECDHE计算秘钥, 利用计算的结果在进行AES加解密的操作.
我现在用生成的数据去计算去计算秘钥是没有问题的. 
但是用文档上的数据, 却得不到跟文档上一样的结果,我还注意到,你的Demo里面生成的公钥都是04开头的, 我这边也加上04, 但是并没有得到我想要的结果.

如果我用测试数据中的一对公私钥, 然后在配合
// 服务端server生成一对公私钥
    NSArray *serverKey = [GMSm2Utils createKeyPair];
    NSString *sPubKey = serverKey[0];
    NSString *sPriKey = serverKey[1];
这样计算的结果竟然一样..我有点不太理解问这是什么原因.这一步可以验证加密曲线肯定是对的,

**Comment by lvzhao666** [comment]
我尝试了一下这个方法
        BIGNUM *x = BN_new();
        BIGNUM *y = BN_new();
        if (EC_POINT_get_affine_coordinates_GFp(group, pub_key, x, y, NULL)) {
            printf("公钥:\n");
            BN_print_fp(stdout, x);
            putc('\n', stdout);
            BN_print_fp(stdout, y);
            putc('\n', stdout);
        }
          
        printf("gen key success:\n the private is %s\n",BN_bn2hex(EC_KEY_get0_private_key(key)));
输出的值x,y, 一个公钥的拆分.. 我想知道为什么有一个04的前缀? 什么意识?  
另外这种加密曲线. 对应demo中的哪个
基于 ECC NIST P-256 曲线(即 secp256r1)进行计算，该曲线的参数详情见:https://www.secg.org/SEC2-
Ver-1.0.pdf
  
"secp256r1": {
"p": 0xffffffff00000001000000000000000000000000ffffffffffffffffffffffff,
"a": 0xffffffff00000001000000000000000000000000fffffffffffffffffffffffc,
"b": 0x5ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b,
"g": (0x6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296,
0x4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5),
"n": 0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551,
"h": 0x1 }

**Comment by muzipiao** [comment]
1. 0x04 代表非压缩，SM2 非压缩公钥格式字节串长度为 65 字节（Hex 格式 130 字节），压缩格式长度为33字节；
2. 你选择的椭圆曲线不对，对比 OpenSSL 源码可知 secp256r1 对应 NID_X9_62_prime256v1，更换为正确的曲线即可；
3. ECDHE 与 ECDH 不同，E 代表临时，每次通讯都随机生成公私钥，是为了前向安全性，概念不容易理解，具体过程 Google。

**Comment by lvzhao666** [comment]
感谢, 感谢, 帮了大忙了..
