### ISSUE TITLE
OpenSSL 冲突

### ISSUE THREAD

**Issue by adolph-suntao** [muzipiao/GMObjC#21]
作者你好，我这是和百度地图openssl冲突，按照你说的升级第三方opebsll库，然后公用一个可以解决。但是我这 和百度地图冲突，不是很明白要怎么和百度地图解决冲突。可以麻烦你指点一下吗？谢谢。我的QQ：1587557282. 如果可以，想加你qq详细了解一下。谢谢！

**Comment by muzipiao** [comment]
百度这个坑已经很多人踩过了，百度依赖的 OpenSSL 版本应该是低于 1.1.1 的，将项目下载后，找到 GMObjCFramework 文件夹，打开工程， Command + B 编译成功后拖入你的项目，使用动态库即可解决。

**Comment by adolph-suntao** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    你好，很感谢你的回复，我这通过你说的，把GMObjCFramework库拖到项目中去，然后手动导入GMObjC 文件，百度地图直接崩溃了。我这是swift项目，不知道你那碰到过这个问题来吗
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                adolph.suntao
                            
                    
                        
                            
                                    adolph.suntao@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2020年07月16日 17:37，CocoaFei<notifications@github.com> 写道： 




百度这个坑已经很多人踩过了，百度依赖的 OpenSSL 版本应该是低于 1.1.1 的，将项目下载后，找到 GMObjCFramework 文件夹，打开工程， Command + B 编译成功后拖入你的项目，使用动态库即可解决。



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
