### ISSUE TITLE
项目崩溃

### ISSUE THREAD

**Issue by adolph-suntao** [muzipiao/GMObjC#22]
你好，通过你说的编译后导入openssl.framework文件，然后手动导入GMObjC，正常情况下是没事的，但是当我们集成BaiduMapKit之后，会报错，请问这该怎样解决呢？QQ：1587557282。麻烦加我一下qq吧，有些问题想请教。

if (!EC_KEY_generate_key(key)) 
地方崩溃
Thread 1: EXC_BAD_ACCESS (code=2, address=0x106ccd3a0)

```
///MARK: - 创建公私钥对

+ (NSArray<NSString *> *)createKeyPair{
    NSArray<NSString *> *keyArray = @[@"", @""];
    EC_GROUP *group = EC_GROUP_new_by_curve_name(NID_sm2); // 椭圆曲线
    EC_KEY *key = NULL; // 密钥对
    do {
        key = EC_KEY_new();
        if (!EC_KEY_set_group(key, group)) {
            break;
        }
        if (!EC_KEY_generate_key(key)) {
            break;
        }
        const EC_POINT *pub_key = EC_KEY_get0_public_key(key);
        const BIGNUM *pri_key = EC_KEY_get0_private_key(key);

        char *hex_pub = EC_POINT_point2hex(group, pub_key, EC_KEY_get_conv_form(key), NULL);
        char *hex_pri = BN_bn2hex(pri_key);
        
        NSString *pubHex = [NSString stringWithCString:hex_pub encoding:NSUTF8StringEncoding];
        NSString *priHex = [NSString stringWithCString:hex_pri encoding:NSUTF8StringEncoding];
        if (pubHex.length > 0 && priHex.length > 0) {
            NSString *priHexWithPadding = [self bnToHexPadding:priHex];
            keyArray = @[pubHex, priHexWithPadding];
        }
        OPENSSL_free(hex_pub);
        OPENSSL_free(hex_pri);
    } while (NO);
    
    if (group != NULL) EC_GROUP_free(group);
    EC_KEY_free(key);
    
    return keyArray;
}
```

**Comment by muzipiao** [comment]
三种集成方式：
1. cocoapods，会自动集成 GMOpenSSL.framework，就是openssl.framework，不需再拖入 openssl.framework；
2. 手动集成，拖入 GMObjC 文件夹的加密类，拖入 openssl.framework 文件就可以了；
3. 手动或者使用 Carthage 编译为动态类 GMObjC.framework 拖入项目，不需要再单独拖入 openssl.framework 。
你集成方式估计不对。

**Comment by adolph-suntao** [comment]
你好，使用Carthage打出来的framework，导入项目可以正常使用，但是打包的时候报错，提示如下：
ld: symbol(s) not found for architecture armv7
查看打出的包支持的架构，不支持armv7，这种该如何解决啊？

**Comment by muzipiao** [comment]
首先，建议移除 armv7 及 arm7s 架构，iPhone 5s 以下的设备基本上都绝迹了，如果确实需要，可按照以下步骤操作：

1. 访问我的另外一个分支[GMOpenSSL](https://github.com/muzipiao/GMOpenSSL)，下载支持 armv7 及 arm7s 的 [openssl.framework](https://codeload.github.com/muzipiao/GMOpenSSL/zip/2.0.3)，在文件夹 GMOpenSSL 中；
2. 将此工程[GMObjC](https://github.com/muzipiao/GMObjC)下载，将`GMObjCFramework/GMObjCFramework`中的 openssl.framework 替换为第一步下载的；
3. 打开 GMObjCFramework 中工程文件 GMObjCFramework.xcodeproj，在 **Build Setting** -> **Valid Architectures**中添加 armv7、armv7s；
4. `cd`切换到 GMObjC 的根目录下，例如下载的 GMObjC 工程在桌面，则执行`cd ~/Desktop/GMObjC`；
5. 执行本地编译命令`carthage build --no-skip-current`，等待完成；
6. 编译完成后，在 GMObjC 文件夹下会有一个 Carthage 文件夹，在里面找到 GMObjC.framework 拖入项目即可。

**Comment by adolph-suntao** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    好的，我试试，万分感谢
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                adolph.suntao
                            
                    
                        
                            
                                    adolph.suntao@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2020年07月28日 17:19，CocoaFei<notifications@github.com> 写道： 



首先，建议移除 armv7 及 arm7s 架构，iPhone 5s 以下的设备基本上都绝迹了，如果确实需要，可按照以下步骤操作：

访问我的另外一个分支GMOpenSSL，下载支持 armv7 及 arm7s 的 openssl.framework，在文件夹 GMOpenSSL 中；
将此工程GMObjC下载，将GMObjCFramework/GMObjCFramework中的 openssl.framework 替换为第一步下载的；
打开 GMObjCFramework 中工程文件 GMObjCFramework.xcodeproj，在 Build Setting -> Valid Architectures中添加 armv7、armv7s；
cd切换到 GMObjC 的根目录下，例如下载的 GMObjC 工程在桌面，则执行cd ~/Desktop/GMObjC；
执行本地编译命令carthage build --no-skip-current，等待完成；
编译完成后，在 GMObjC 文件夹下会有一个 Carthage 文件夹，在里面找到 GMObjC.framework 拖入项目即可。


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
