### ISSUE TITLE
ios端和安卓端加密结果不一样？怎么修正？

### ISSUE THREAD

**Issue by hms040717007** [muzipiao/GMObjC#23]

**Comment by muzipiao** [comment]
不可能一样的，相同明文，iOS 端 SM2 加密每次结果也都是不一样的，原因在于每次加密都会取随机数 k，原理看国密里面的官方文档和下方这个链接。
[SM2 加密理解](http://cocoafei.top/2019/08/iOS-%E4%BD%BF%E7%94%A8-SM2-SM4-%E5%8A%A0%E8%A7%A3%E5%AF%86-SM2-%E7%AD%BE%E5%90%8D%E9%AA%8C%E7%AD%BE%E5%8F%8A-SM3-%E6%91%98%E8%A6%81/)
