### ISSUE TITLE
error read memory failed

### ISSUE THREAD

**Issue by NSLog-YuHaitao** [muzipiao/GMObjC#26]
1、百度地图6.0.0版本,解决OpenSSL冲突问题
2、GMObjC 3.1.2版本
集成以上两个SDK版本,运行程序直接报error read memory failed,请作者看一下什么原因

**Comment by muzipiao** [comment]
当集成有百度地图或其他包含旧版本 OpenSSL 库时，不要使用 cocoapods 集成 GMObjC，具体查看 README 说明。

> 将 GMObjC 编译为动态库可解决此类冲突。动态库项目在 GMObjCFramework 文件夹中，打开项目执行  `command + b`  编译为真机/模拟器版本动态库，根据需要合并；也可以通过 Carthage 自动将 GMObjC 编译动态库，具体操作看下一步。

**Comment by NSLog-YuHaitao** [comment]
百度6.0.0 好像解决OpenSSL冲突问题了

**Comment by muzipiao** [comment]
百度使用的 OpenSSL 仍旧是低版本，通过反编译百度地图依赖的 OpenSSL 编译文件 libcrypto.a，可以发现版本仍旧是 `OpenSSL 1.0.2e 3 Dec 2015`，而国密最低要求是 OpenSSL 1.1.1 及以上版本。

**Comment by NSLog-YuHaitao** [comment]
我问题客服确实是没有修复,说国庆前后会修复
