### ISSUE TITLE
RN项目里OpenSSL-Universal和GMOpenSSL 冲突吗？

### ISSUE THREAD

**Issue by matuanc** [muzipiao/GMObjC#27]
![image](https://user-images.githubusercontent.com/33281802/93575440-3b320580-f9cc-11ea-9e68-242cbfe9b99c.png)

项目里使用的时候用抓包工具 显示 传了参数，但是 密钥为空

**Comment by muzipiao** [comment]
冲突，OpenSSL-Universal 的 OpenSSL 版本 是 1.0.2.20，而 GMOpenSSL 是最新的 1.1.1g 版本，二者都是 OpenSSL，会冲突

**Comment by matuanc** [comment]
> 两者都是OpenSSL，会冲突
我用的你直接集成的方法，但是没成功，所以我想 去掉 GMOpenSSL这个包可以吗？
因为React Native的OpenSSL这个是自带的去不掉。
如果可以文档能在详细点吗？
谢谢！
![image](https://user-images.githubusercontent.com/33281802/93595816-02555900-f9eb-11ea-8697-96cb776272e0.png)

**Comment by muzipiao** [comment]
1. 不集成 GMOpenSSL 是可以的，GMObjC 使用任何 OpenSSL 1.1.1 以上版本即可；
2. 确保 React Native 的 OpenSSL 版本大于 1.1.1 即可，GMOpenSSL 版本是 1.1.1g；
3. 区分 RN 项目导入头文件方式以`#import <openssl/sm2.h>`类似方式；
4. RN 项目不太了解，如果你想使用 GMObjC 的话，它是开源的，可以任意修改使用。
