### ISSUE TITLE
GMObjc.framework不支持armv7架构

### ISSUE THREAD

**Issue by feiyuba** [muzipiao/GMObjC#28]
GMObjc.framework不支持armv7架构

**Comment by muzipiao** [comment]
iPhone 5s以下的设备现在基本上找不到了，所以没必要再支持 armv7；
如果想支持 armv7，开源项目，手动更改一下，编译集成即可，步骤如下：
1. 下载支持 armv7 的 OpenSSL 版本，对应 [GMOpenSSL](https://github.com/muzipiao/GMOpenSSL) 2.0.3，2.0.3 版本支持 armv7 和 armv7s，pod 文件指定版本`pod 'GMOpenSSL', '2.0.3'` 即可，或下载对应 tag 文件。
2. 手动集成时将下载的 GMOpenSSL 项目中支持 armv7 的 openssl.framework 替换 GMObjC 项目的 openssl.framework，在 GMObjC 的工程配置文件 Target->Build Settings 的`VALID_ARCHS`项中，双击编辑添加`armv7 armv7s`架构即可。
