### ISSUE TITLE
missing required architecture armv7

### ISSUE THREAD

**Issue by aiquantong** [muzipiao/GMObjC#29]
ld: warning: ignoring file /Users/aiquantong/Documents/me/code/jianhua.git/code/Pods/GMOpenSSL/GMOpenSSL/openssl.framework/openssl, missing required architecture armv7 in file /Users/aiquantong/Documents/me/code/jianhua.git/code/Pods/GMOpenSSL/GMOpenSSL/openssl.framework/openssl (3 slices)

**Comment by muzipiao** [comment]
Most frameworks no longer support armv7. If you need to support armv7, edit the Podfile file and specify the GMOpenSSL version.

`pod'GMOpenSSL', '2.0.3'`

If you install manually:
1. Download the release 2.0.3 version of GMOpenSSL and replace openssl.framework in the GMObjC project;
2. Edit the project configuration file `Target->Build Settings` in the `VALID_ARCHS` item, double-click to edit and add `armv7 armv7s` architecture.
