### ISSUE TITLE
R+S加签

### ISSUE THREAD

**Issue by lztbwlkj** [muzipiao/GMObjC#3]
加签后的数据长度是固定的128位吗？

**Comment by muzipiao** [comment]
签名结果不是固定长度，大概率为128位，也可能为其他长度。

**Comment by lztbwlkj** [comment]
去掉"，"号后[NSString stringWithFormat:@"%@%@", R, S]这样拼接起来对结果不会有影响吧

**Comment by muzipiao** [comment]
1. 看后端怎么验签了，验签时是需要区分R和S的，如果不加逗号，可能区分的R、S不正确。R和S转Hex后大概率都是64字节，R可能是62字节，S也有可能是62字节。
2. 所以，如果R和S都是64字节，你把128字节的结果传给后端，后端分别截取前后64字节来获取R、S的值验签正确；如果结果为126字节，那R和S都有可能为62字节，后端截取不正确，验签就不正确了。
3. 库中的随机数 K 每次是变化的，所以每次签名结果都不相同，可以参考SM2官方文档第五章。

**Comment by lztbwlkj** [comment]
感谢🙏 ，明白了

**Comment by muzipiao** [comment]
Java调用toByteArray默认编码机制为iso-8859-1，而ios字符串默认编码机制为utf-8，所以必须有一方做出转换，所以最好后端转utf-8。如果不方便，你可尝试后端传Data二进制数据，客户端使用`NSString *utf8Str = [[NSString alloc]initWithData:data encoding:NSUTF16BigEndianStringEncoding];`，可转为普通utf-8字符串。

**Comment by lztbwlkj** [comment]
虽然国密有自己的一套坐标,阶n，k等数据，但还是希望能支持自定义，这样在调试的时候就更方便确定问题

**Comment by lztbwlkj** [comment]
我不知道你的SM2加签对待签名文本是如何处理的，我这边就是怎么都验证不通过，后来我换了这个SDK验签成功了，分享给你，希望你可以完善这个库！！
[SM2-master 2.zip](https://github.com/muzipiao/GMObjC/files/3849974/SM2-master.2.zip)
（如果你乐意告知我是哪里出错了也感激不尽）

**Comment by muzipiao** [comment]
你发这个Demo我看了，可以判断是你们后端在验签的时候，把不是16进制的字符串进行了16进制解码。这个Demo的API要求传入的全部是16进制字符串格式，而你传入的是错误的未进行16进制编码的明文，相同的错误，导致了相同的签名结果。但这样做，若明文长度为奇数或有特殊字符的情况下，可能会出现未知错误。
举例：明文密码为123456，进行16进制编码后313233343536，同理userID明文为lifei_zdjl@126.com，16进制编码后6C696665695F7A646A6C403132362E636F6D，你使用GMSm2Utils明文进行签名，后端或者你发这个Demo使用16进制编码后的字段进行验签，二者相互校验结果一致。

**Comment by muzipiao** [comment]
可以固定为 128 位，BIGNUM 转 Hex 不足 64 位时，可以在前面补 0 ，不影响结果。
