### ISSUE TITLE
openssl冲突

### ISSUE THREAD

**Issue by CoderTonyChan** [muzipiao/GMObjC#31]
由于老项目用到RSA加密 依赖的库用到RSA_size等方法 我把GMObjC.framework在Link Binary With Libraries中拖到最后 

编译运行的时候没问题 但是Archive的时候 打包没问题 运行还是报错 

或者有无办法将RSA相关的方法干掉？

这个是不是Other Linker Flag -ObjC的功能 有无方法单独GMObjC.framework不添加-ObjC进行编译？

有空帮忙看看吗？谢谢！

**Comment by muzipiao** [comment]
1. GMObjC.framework 库不需要加入 -ObjC 标记；
2. 其他库需要加入 -ObjC 标记，但项目无法加入 -ObjC 标记时，可使用 -force_load 逐个库设置
3. 例如 libx.a liby.framework 需要加入 -ObjC 标记，则在 Other Linker Flag 中设置如下(-force_load 单独一行)：
```objc
-force_load
$(SRCROOT)/folder_path/folder_subpath/libx.a
-force_load
$(SRCROOT)/folder_path/folder_subpath/liby.framework/liby
```
