### ISSUE TITLE
java 端的sm2p256v1 对应库里的哪个曲线呢？

### ISSUE THREAD

**Issue by suckerSlayer** [muzipiao/GMObjC#32]

**Comment by muzipiao** [comment]
GMSm2Def.h 头文件里面有详细注释，默认就是 sm2p256v1，不用设置
* sm2p256v1（对应 OpenSSL 中 NID_sm2）
* secp256k1（对应 OpenSSL 中 NID_secp256k1）
* secp256r1（对应 OpenSSL 中 NID_X9_62_prime256v1）

**Comment by suckerSlayer** [comment]
我通过 EC_POINT_mul 这个方法来从java给我私钥计算出公钥，发现公钥结果和java端那边的不一致，我这边公钥是130的hex码，java那边的公钥无论是base64（44字符）还是hex（字符）都比我短得多

**Comment by muzipiao** [comment]
首先理解椭圆曲线的公钥私钥是什么，国密 SM2 的私钥是一个大整数，公钥是一个点坐标。

公钥 (Gx, Gy) 和私钥 d 转 Hex 格式时，Gx, Gy, d 都是 BIGNUM 类型，逐个转 Hex 一般为 64 字符，不足 64 字符的情况下需要在前面补0（Java端可参考 bouncycastle 库密钥转码补齐规则），这样公钥长度为 128 字符，私钥 64 字符。

公钥一般使用非压缩格式，前面加 04 代表非压缩格式，即 公钥=04GxGy，所以可能是后端采用了压缩格式或转码错误。

参考我的一篇博客理解 [SM2 原理](https://cocoafei.top/2019/08/iOS-%E4%BD%BF%E7%94%A8-SM2-SM4-%E5%8A%A0%E8%A7%A3%E5%AF%86-SM2-%E7%AD%BE%E5%90%8D%E9%AA%8C%E7%AD%BE%E5%8F%8A-SM3-%E6%91%98%E8%A6%81/)

**Comment by suckerSlayer** [comment]
好的，多谢！我来看看先

**Comment by suckerSlayer** [comment]
现在公私钥确实保持一致了，不过签名位数却不同，java端是140位hex，iOS这边是128的hex, 造成差异的原因可能是什么呢

**Comment by zhouzezhou** [comment]
作者你好！！请问公钥加密后的c1c3c2格式密文怎么转换成c1c2c3格式的密文提供给服务端呢？

**Comment by muzipiao** [comment]
参考 Readme-CN.md 的【ASN1 编码解码】章节。

**Comment by zhouzezhou** [comment]
> 参考 Readme-CN.md 的【ASN1 编码解码】章节。

感谢！！！祝好！

**Comment by zhouzezhou** [comment]
另外想请教作者，有没有Objective-c版本的sm3的hmac算法呀？我为了这个这几天可苦恼了

**Comment by muzipiao** [comment]
看着方法简单，没加到库里面，有空我整理一下加上去
```objc
#import <openssl/hmac.h>
#import <openssl/sm3.h>

- (NSString *)hmacWithSM3:(NSData *)keyData text:(NSData *)txtData {
    uint8_t *keyBytes = (uint8_t *)keyData.bytes;
    uint8_t *txtBytes = (uint8_t *)txtData.bytes;
    uint8_t *result = HMAC(EVP_sm3(), keyBytes, (int)keyData.length, txtBytes, (int)txtData.length, NULL, NULL);
    
    NSMutableString *resultHex = [NSMutableString stringWithCapacity:SM3_DIGEST_LENGTH];
    for (NSInteger i = 0; i < SM3_DIGEST_LENGTH; i++) {
        NSString *subHex = [NSString stringWithFormat:@"%02x",result[i]];
        [resultHex appendString:subHex];
    }
    return resultHex;
}
```

**Comment by zhouzezhou** [comment]
> 看着方法简单，没加到库里面，有空我整理一下加上去
> 
> ```objc
> #import <openssl/hmac.h>
> #import <openssl/sm3.h>
> 
> - (NSString *)hmacWithSM3:(NSData *)keyData text:(NSData *)txtData {
>     uint8_t *keyBytes = (uint8_t *)keyData.bytes;
>     uint8_t *txtBytes = (uint8_t *)txtData.bytes;
>     uint8_t *result = HMAC(EVP_sm3(), keyBytes, (int)keyData.length, txtBytes, (int)txtData.length, NULL, NULL);
>     
>     NSMutableString *resultHex = [NSMutableString stringWithCapacity:SM3_DIGEST_LENGTH];
>     for (NSInteger i = 0; i < SM3_DIGEST_LENGTH; i++) {
>         NSString *subHex = [NSString stringWithFormat:@"%02x",result[i]];
>         [resultHex appendString:subHex];
>     }
>     return resultHex;
> }
> ```

啊啊啊！！原来HMAC()里的可以直接把EVP_sm3()传进去，我刚开始想到了，怎么就没试一下呢！！非常感谢作者，辛苦你了！感谢感谢感谢
