### ISSUE TITLE
你好，打包的时候报这个错 应该怎么处理

### ISSUE THREAD

**Issue by SmallWeed** [muzipiao/GMObjC#33]
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_GMSm2Utils", referenced from:
      objc-class-ref in Security.o
ld: symbol(s) not found for architecture armv7

**Comment by muzipiao** [comment]
GMObjC 依赖的 GMOpenSSL 默认不支持 armv7，下载对应 2.0.3 版本，2.0.3 版本支持 armv7 和 armv7s，pod 文件指定版本`pod 'GMOpenSSL', '2.0.3'` 即可，或下载对应 tag 文件。

链接：[GMOpenSSL](https://github.com/muzipiao/GMOpenSSL)

**Comment by SmallWeed** [comment]
![WeChat8c87fd2d205e8d3416b4f22302d58e82](https://user-images.githubusercontent.com/11731944/103268104-e4d25b00-49ed-11eb-869f-845027d084ce.png)
![WeChate5c472b521cf11afbca74c3305ce69e7](https://user-images.githubusercontent.com/11731944/103268136-f3b90d80-49ed-11eb-8678-4efd35ec68fd.png)
![631609213198_ pic](https://user-images.githubusercontent.com/11731944/103268148-fca9df00-49ed-11eb-84b1-e162b6bc280a.jpg)

你好，我按照你说的 pod 集成了 2.0.3  但是打包的时候 还是显示这个

**Comment by SmallWeed** [comment]
能加下我的QQ 491041442 指导我下吗
