### ISSUE TITLE
carthage编译会报错，然后在GMObjCFramework下真机可以编译，模拟器不行

### ISSUE THREAD

**Issue by TheCodeor** [muzipiao/GMObjC#34]
openssl.framework  opensslconf.h 文件报错 Unable to determine target or target not included in OpenSSL build

**Comment by muzipiao** [comment]
这是 Xcode 12 引起的，已修复。Carthage 默认下载的是最新的 tag，修复后忘记打 tag 了，下载项目后 cd 到项目目录，使用`carthage build --no-skip-current`本地编译即可。

**Comment by TheCodeor** [comment]
不太好用 不过我把GMObjCFramework的arm64 改成x86 后模拟器能编译出来，暂时能用，谢谢。辛苦了

**Comment by muzipiao** [comment]
已经打了 tag，执行`carthage update`可编译；Xcode 12 可能会遇到编译错误，readme 说明文档中有常见错误说明
