### ISSUE TITLE
pod 一直失败

### ISSUE THREAD

**Issue by LCBbest** [muzipiao/GMObjC#36]
pod 一直失败

**Comment by muzipiao** [comment]
这个是由于墙的原因导致，最简单的办法使用梯子更新。
如果没有梯子，另一个方法就是本地编译，下载本项目，打开 GMObjCFramework 文件夹，将 xcframework.sh 拖入终端运行，结束后生成`build/GMObjC.xcframework`，将 GMObjC.xcframework 拖入项目即可使用。

**Comment by LCBbest** [comment]
现在pod下来了 感谢。我看文档中说与百度地图sdk 冲突，项目中使用百度地图sdk ，的确启动报错，有没有具体的解决方法呢。怎么更改百度地图 sdk的 openssl

**Comment by muzipiao** [comment]
使用动态库可解决冲突，使用 carthage 编译为 GMObjC.framework
或按照上面的方法编译为 GMObjC.xcframework 都可解决，不使用 cocoapods，拖入项目集成。

**Comment by xudogn** [comment]
使用了梯子也还是pod失败呢
