### ISSUE TITLE
pod 后报这个错误，手动集成也报同样错误

### ISSUE THREAD

**Issue by zengjinzong** [muzipiao/GMObjC#38]
<img width="646" alt="截屏2021-01-18 下午3 28 38" src="https://user-images.githubusercontent.com/13520124/104884985-398c4480-59a2-11eb-96b8-e7435fb933ed.png">

**Comment by zengjinzong** [comment]
dyld: Library not loaded: @rpath/GMObjC.framework/GMObjC
  Referenced from: /private/var/containers/Bundle/Application/E2E0BFC1-852F-4E0B-8642-634D9D3F7A1B/eemp.app/eemp
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/GPUTools.framework/libglInterpose.dylib:/usr/lib/libMTLCapture.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib

**Comment by muzipiao** [comment]
1. Command + Shift + k 清理工程；
2. 清空 /Users/xx/Library/Developer/Xcode/DerivedData 目录；
3. 通过`file GMObjC.framework/GMObjC` 查看是动态库还是静态库；
4. General – Frameworks, Libraries, and Embedded Content - 动态库选择 Embed & Sign。
