### ISSUE TITLE
GMObjC.framework 动态库

### ISSUE THREAD

**Issue by VonKeYuan** [muzipiao/GMObjC#39]
将 GMObjC.framework 设置为 Embed & Sign，编译运行项目时，xcode提示Unable to install，将动态库删除后项目正常运行，希望大神给个解决方案。
xcode版本：12.3

**Comment by muzipiao** [comment]
把错误日志贴出来

**Comment by VonKeYuan** [comment]
Details

Unable to install "MTManager"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620388
--
No code signature found.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620388
User Info: {
    DVTRadarComponentKey = 261622;
    MobileDeviceErrorCode = "(0xE800801C)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x000000011f246c8f DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x000000011f285241 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 155
	2   DVTFoundation                       0x000000010196664b DVTInvokeWithStrongOwnership + 71
	3   DTDeviceKitBase                     0x000000011f284f82 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1440
	4   IDEiOSSupportCore                   0x000000011f0f5a10 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.292 + 3513
	5   DVTFoundation                       0x0000000101a9517e __DVT_CALLING_CLIENT_BLOCK__ + 7
	6   DVTFoundation                       0x0000000101a96da0 __DVTDispatchAsync_block_invoke + 1191
	7   libdispatch.dylib                   0x00007fff201e25dd _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff201e37c7 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff201e95fe _dispatch_lane_serial_drain + 606
	10  libdispatch.dylib                   0x00007fff201ea0cb _dispatch_lane_invoke + 375
	11  libdispatch.dylib                   0x00007fff201f3c5d _dispatch_workloop_worker_thread + 819
	12  libsystem_pthread.dylib             0x00007fff2038b499 _pthread_wqthread + 314
	13  libsystem_pthread.dylib             0x00007fff2038a467 start_wqthread + 15
);
}
--


System Information

macOS Version 11.1 (Build 20C69)
Xcode 12.3 (17715) (Build 12C33)
Timestamp: 2021-01-19T14:10:22+08:00

**Comment by VonKeYuan** [comment]
> 把错误日志贴出来

Details

Unable to install "MTManager"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620388
No code signature found.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620388
User Info: {
DVTRadarComponentKey = 261622;
MobileDeviceErrorCode = "(0xE800801C)";
"com.apple.dtdevicekit.stacktrace" = (
0 DTDeviceKitBase 0x000000011f246c8f DTDKCreateNSErrorFromAMDErrorCode + 220
1 DTDeviceKitBase 0x000000011f285241 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 155
2 DVTFoundation 0x000000010196664b DVTInvokeWithStrongOwnership + 71
3 DTDeviceKitBase 0x000000011f284f82 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1440
4 IDEiOSSupportCore 0x000000011f0f5a10 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.292 + 3513
5 DVTFoundation 0x0000000101a9517e DVT_CALLING_CLIENT_BLOCK + 7
6 DVTFoundation 0x0000000101a96da0 __DVTDispatchAsync_block_invoke + 1191
7 libdispatch.dylib 0x00007fff201e25dd _dispatch_call_block_and_release + 12
8 libdispatch.dylib 0x00007fff201e37c7 _dispatch_client_callout + 8
9 libdispatch.dylib 0x00007fff201e95fe _dispatch_lane_serial_drain + 606
10 libdispatch.dylib 0x00007fff201ea0cb _dispatch_lane_invoke + 375
11 libdispatch.dylib 0x00007fff201f3c5d _dispatch_workloop_worker_thread + 819
12 libsystem_pthread.dylib 0x00007fff2038b499 _pthread_wqthread + 314
13 libsystem_pthread.dylib 0x00007fff2038a467 start_wqthread + 15
);
}
System Information

macOS Version 11.1 (Build 20C69)
Xcode 12.3 (17715) (Build 12C33)
Timestamp: 2021-01-19T14:10:22+08:00

**Comment by muzipiao** [comment]
1. Command + Shift + k 清理工程，清空 /Users/xx/Library/Developer/Xcode/DerivedData 目录下文件；
2. 把应用从手机上删除，重启 Xcode，然后再运行安装 MTManager。

**Comment by VonKeYuan** [comment]
> 1. Command + Shift + k 清理工程，清空 /Users/xx/Library/Developer/Xcode/DerivedData 目录下文件；
> 2. 把应用从手机上删除，重启 Xcode，然后再运行安装 MTManager。

都试过了，电脑都重启了，还是不好用...

**Comment by muzipiao** [comment]
使用动态库可解决冲突，使用 carthage 编译为 GMObjC.framework
或按照上面的方法编译为 GMObjC.xcframework 都可解决，不使用 cocoapods，拖入项目集成。

**Comment by VonKeYuan** [comment]
都试了一遍，第二个方法好用，最后考虑第二个方法的原因是因为GitHub太慢了，后来是用的carthage加载本地资源制作的framework。万分感谢！
