### ISSUE TITLE
新版本不支持armv7，引入工程后，可以模拟器运行，但是打包link报错怎么处理啊，报错日志如下

### ISSUE THREAD

**Issue by HiGe-139** [muzipiao/GMObjC#40]
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_GMSm4Utils", referenced from:
      objc-class-ref in URLSingleton.o
  "_OBJC_CLASS_$_GMSm3Utils", referenced from:
      objc-class-ref in URLSingleton.o
  "_OBJC_CLASS_$_GMSm2Utils", referenced from:
      objc-class-ref in URLSingleton.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by muzipiao** [comment]
市场上几乎找不到 armv7 的手机，建议工程里移除，若不想移除，可使用如下方法：
1. 使用 cocoapods 集成时，指定 GMOpenSSL 版本；
```
pod 'GMOpenSSL', '2.2.0'
pod 'GMObjC'
```
2. 若手动集成，拖入 GMObjC 源码至工程，并下载 [GMOpenSSL](https://github.com/muzipiao/GMOpenSSL) 的 [2.2.0](https://codeload.github.com/muzipiao/GMOpenSSL/zip/2.2.0) 版本，拖入工程；
3. 若使用 Carthage 集成，同样原理，替换支持 armv7 的 [GMOpenSSL](https://github.com/muzipiao/GMOpenSSL) ，本地编译。

**Comment by HiGe-139** [comment]
由于SM2签名算法userID我们不需要默认值，需要修改库里面部分源码，只能选择手动集成，我手动换了 GMOpenSSL 的 2.2.0 版本，发现在模拟器上运行不了，手动合并的framework又会签名报错IPA processing failed，请大佬再指点一下

**Comment by muzipiao** [comment]
你不把错误 日志/log 贴出来，让我掐指算么...
常见的 Xcode 12 模拟器不能运行，[readme](https://github.com/muzipiao/GMObjC/blob/master/README-CN.md) 文档里面有说明，其他错误根据日志 Google 解决即可。

**Comment by HiGe-139** [comment]
Thread 1: EXC_BAD_ACCESS (code=2, address=0x1065c4660)

**Comment by HiGe-139** [comment]
Thread 1: EXC_BAD_ACCESS (code=2, address=0x1065c4660)

**Comment by HiGe-139** [comment]
Thread 1: EXC_BAD_ACCESS (code=2, address=0x1065c4660)

用pod 'GMOpenSSL', '2.2.0'，拖入 GMObjC 源码至工程，然后模拟器运行直接报这个错，控制台没有日志

**Comment by muzipiao** [comment]
可能是改动或集成方式问题：
1. 只使用 cocoapods，不改动源码直接全部用 pod 集成尝试，若解决为改动原因导致；
2. 只使用源码，拖入 GMObjC 源码和 openssl.framework 至项目，若解决为混合集成导致。
```
pod 'GMOpenSSL', '2.2.0'
pod 'GMObjC'
```

**Comment by HiGe-139** [comment]
只使用 cocoapods和只使用源码这两种方式都尝试过了，都是一样的问题，模拟器运行就会crash

**Comment by HiGe-139** [comment]
使用手动编译为framework的方式如果只编译真机的，则模拟器无法运行，真机和模拟器的合并到一块，打包导出又报IPA processing failed

**Comment by muzipiao** [comment]
[Building for iOS, but the linked and embedded framework 'GMObjC.framework' was built for iOS + iOS Simulator.](https://stackoverflow.com/questions/63267897/building-for-ios-simulator-but-the-linked-framework-framework-was-built)

[building for iOS Simulator, but linking in object file built for iOS](https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios)

**Comment by HiGe-139** [comment]
这两个我都试过了，无法解决问题，现在我只能保留真机的framework，然后调试使用真机调试，模拟无法使用，我感觉是SDK配置的问题，我之前是xcode12.3，现在升到12.4也还是不行。您方便加下QQ吗，244454783我QQ
