### ISSUE TITLE
SM2签名 私钥加密数据时报错

### ISSUE THREAD

**Issue by luckbird** [muzipiao/GMObjC#41]
![image](https://user-images.githubusercontent.com/11241445/112783621-4f914200-9082-11eb-9199-a03d92687cb9.png)
单独拎出来或者放置于其他项目都能正常运行，放置于自己项目报错。是否和其他内容有所冲突？

**Comment by muzipiao** [comment]
GMObjC 是依赖 OpenSSL 1.1.1 以上版本的，其他 SDK 如百度地图，也编译了低版本的 OpenSSL，运行时链接了低版本的库，导致报错，解决版本在 readme 里面有，编译为动态库 framewrok 或者 xcframework。

推荐 xcframework，在`GMObjC/GMObjCFramework`文件夹下，将xcframework.sh拖入终端回车，运行完毕，编译完成目标为`GMObjC/GMObjCFramework/build/GMObjC.xcframework`，将GMObjC.xcframework动态库集成至项目即可。
