### ISSUE TITLE
编译动态库，获取的framework无法使用

### ISSUE THREAD

**Issue by caijichang** [muzipiao/GMObjC#42]
我在工程里的GMObjC.framework里command+b得到的framework时，使用sm2加密，加密出的都是nil，但是使用xcframework是可以使用sm2加密的。
由于我们的项目无法使用xcframwork，并且openssl版本冲突，只能使用framework。所以我该如何获得正确的framework呢

**Comment by muzipiao** [comment]
使用 Carthage 编译，readme 中有介绍，GitHub网络不好，可以本地编译：
1. 安装`brew update && brew install carthage`；
2. 下载此项目，并 cd 到此项目目录下；
3. 执行`carthage build --no-skip-current`本地编译；
4. 编译成功的 GMObjC.framework 在当前工程目录的Carthage/Build/iOS下面。
