### ISSUE TITLE
SM4 不能设置填充方式吗？

### ISSUE THREAD

**Issue by mark2L** [muzipiao/GMObjC#44]
服务端目前使用的是NO_PADDING
目前我使用的处理办法就是在加密的时候把pad_en 改为 0 。

**Comment by muzipiao** [comment]
这样是不对的，当你的明文长度 byte 不是 16 的倍数的时候，可能导致无法解密或者错误，这是因为 SM4 加密块要求必须是 16 的倍数。
如果你想把 pad_en 改为 0 实现正确加解密，你可以把明文先填充为16的倍数，解密后删除填充的内容即可。
例如，密码为123456，你先对明文进行填充000000000012456，解密后删除前面填充的0即可。
