### ISSUE TITLE
求问sm2加签验签

### ISSUE THREAD

**Issue by qqbzg** [muzipiao/GMObjC#45]
感谢muzipiao终于让我找到一个靠谱的国密oc库和demo。
但关于sm2的加签验签，这里有问题求问。
这边我们希望使用的是sm3withsm2（类似sha256withRSA），
demo里面的例子，我看到digest使用的是EVP_sm3。
这里我可否理解这个加签验签的事例其实就是 sm3withsm2？
我理解上有什么纰漏，也烦请指出。

**Comment by muzipiao** [comment]
可以简单这么理解。
签名验签就是一个身份验证过程，你可以搜索一下ECDH会了解更多；
EVP_sm3 是指签名验签的 HASH 算法使用 sm3，OpenSSL 默认 sm3；
GMObjC 开源库不复杂，你想使用其他HASH算法，直接修改替换 EVP_sm3 即可，结果不变；
eg:
EVP_sha1
EVP_sha224
EVP_sha256
EVP_sha384
EVP_sha512

**Comment by qqbzg** [comment]
> 可以简单这么理解。
> 签名验签就是一个身份验证过程，你可以搜索一下ECDH会了解更多；
> EVP_sm3 是指签名验签的 HASH 算法使用 sm3，OpenSSL 默认 sm3；
> GMObjC 开源库不复杂，你想使用其他HASH算法，直接修改替换 EVP_sm3 即可，结果不变；
> eg:
> EVP_sha1
> EVP_sha224
> EVP_sha256
> EVP_sha384
> EVP_sha512

非常感谢~
这里关于sm2公私钥编码处理这块儿还想请教一下。demo里面是直接生产了sm2的公私钥，私钥是大数，公钥是曲线点。
我这里是本地生成的公私钥 pem 文件（base64），具体如下。

![image](https://user-images.githubusercontent.com/6121793/114402591-903aa080-9bd6-11eb-9e85-391fef8cd8d0.png)

我这边存疑的问题是，如果我直接读取公私钥的的 pem 文件，然后转 hex，我希望得到的是如下的十六进制string：（priv，如上图）
    76:02:07:62:7b:68:13:36:5c:e4:6b:88:40:36:bc:
    3e:41:2e:f1:41:d3:ae:c8:d0:8c:6c:fa:00:63:6c:
    e7:4f

但我得到的是：
308187020100301306072A8648CE3D020106082A811CCF5501822D046D306B0201010420**_760207627B6813365CE46B884036BC3E412EF141D3AEC8D08C6CFA00636CE74F_**A14403420004667F24684B27E8203949A7ECABF8BE8352F448BE5C20F224516BC2900E44BE901015D30E4FB47530F35602A61E3C182FCFA88C10E9C3C3D6106D99B05C422065

然后我在这串里面找了半天，确实找到了真正的priv的部分，是个子串。（也尝试了asn1解码，无果）

想请教如何根据pem文件得到公私钥？objective-c这块儿我暂时没找到好的解决办法。。

**Comment by muzipiao** [comment]
首先弄清楚两个概念：
1. der 编码格式是 asn1 编码标准的一种实现形式，der 就是密钥的二进制表述格式；
2. pem 格式就是对 der 编码转码为 base64 字符格式，通过 base64 解码可以还原 der 格式;
3. openssl 是使用 asn1 对密钥进行编码的，这里生成的 pem 私钥就是 der(asn1) 编码格式；
4. GMObjC 中的 asn1 编码解码是针对密文的，对密钥编码不适用，你想实现需要重新定义 ASN1_SEQUENCE，较麻烦；
5. 没必要对 pem 密钥进行 asn1 解码，pem 转 der 后，可通过私钥直接算出公钥，这样就获取了公私钥，可正常使用；

这里给你示例怎么从私钥算出公钥，读取 pem 字符后，base64 解码为 NSData，转16进制字符串传入方法获取公钥。

```oc
+ (nullable NSString *)calcPubKey:(NSString *)privateKey{
    if (privateKey.length == 0) {
        return nil;
    }
    const char *private_key = privateKey.UTF8String;
    EC_GROUP *group = EC_GROUP_new_by_curve_name(kDefaultEllipticCurveType);
    BIGNUM *pri_num = NULL;  // 私钥
    EC_POINT *pub_point = NULL; // 公钥坐标
    EC_KEY *key = NULL; // 密钥对
    NSString *publicKey = nil;  // 计算出的公钥
    do {
        if (!BN_hex2bn(&pri_num, private_key)) {
            break; // 私钥转 BIGNUM
        }
        key = EC_KEY_new();
        if (!EC_KEY_set_group(key, group)) {
            break;
        }
        if (!EC_KEY_set_private_key(key, pri_num)) {
            break; // 设置私钥
        }
        pub_point = EC_POINT_new(group);
        if (!EC_POINT_mul(group, pub_point, pri_num, NULL, NULL, NULL)) {
            break; // 私钥算出公钥
        }
        if (!EC_KEY_set_public_key(key, pub_point)) {
            break; // 设置公钥
        }
        char *hex_pub = EC_POINT_point2hex(group, pub_point, EC_KEY_get_conv_form(key), NULL);
        
        publicKey = [NSString stringWithCString:hex_pub encoding:NSUTF8StringEncoding];
        OPENSSL_free(hex_pub);
    } while (NO);
    
    if (group != NULL) EC_GROUP_free(group);
    EC_POINT_free(pub_point);
    EC_KEY_free(key);
    BN_free(pri_num);
    
    return publicKey;
}
```

**Comment by qqbzg** [comment]
这边我一直想要解决的，是如果通过读入通用的 pem 密钥（比如服务端生成），然后继续开展sm2的加签和验签。

遇到的难点也是怎么读这个pem？

```
//下面是私钥pem中的内容

NSString* aa = @"MIGHAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBG0wawIBAQQgeIGYT4/G3YdkcaaJ3QRmCllSZC58idDhgOdnrlFLdRChRANCAAT2GsaJ4OPF6qoj+h8deYd4Dh2mY5PqM2gdrZYB89KMZ85bxwZ9IKxUd38w8OBhhlNfnHBpUGE3kDTV2iHsQ5Is";

//转换为nsdata

NSData *ab = [[NSData alloc] initWithBase64EncodedString:aa options:0];

//转换为16进制

NSString* ac = [GMUtils dataToHex:ab];
```

但这里转换完成的hex值并不是真正的我们想要的私钥值。

找到了一篇 java 处理的文章 https://blog.csdn.net/shenshiheng2006/article/details/103959453

把里面的数据带入，ios这边处理的话我最多能走到base64转到hex格式，然后再进去相关读取就卡住了。但是从pem读入私钥是比较通用的场景，非常头秃，特求大佬解答。

**Comment by muzipiao** [comment]
私钥打包进去就泄密了，千万不要这样做，PEM 格式的公钥是 ASN1 编码，通过 BIO 就可以解码编码，明天我先给你写一个示例，我尽量这周末把 PEM 格式支持加到 GMObjC 里面。

**Comment by muzipiao** [comment]
这是直接读取PEM密钥的方法：

**Comment by qqbzg** [comment]
大赞！！完美解决我的需求！！感谢大佬～

**Comment by muzipiao** [comment]
离大佬还远，会者不难，刚好研究过这方面而已，抽空给点点start就可以了

**Comment by qqbzg** [comment]
非常感谢
