### ISSUE TITLE
请教，后台提供key文件的公钥无法用于加密

### ISSUE THREAD

**Issue by Lshenshi** [muzipiao/GMObjC#46]
后台提供.key文件的公钥，解析读取后，得到格式为
-----BEGIN PUBLIC KEY-----
MFkwEwYHK...(中间忽略)....QbJMgIT
PzAYl4qN...(中间忽略)....1JxIw+TXf/R9/jSkkkA==
-----END PUBLIC KEY-----
我把上下两端字符串按照教程传输进去：
NSArray *pubKey = @"MFkwEwYHK...(中间忽略)....QbJMgIT""PzAYl4qN...(中间忽略)....1JxIw+TXf/R9/jSkkkA==";
感觉格式明显对不上。
果然，加密@"123456"的结果返回为nil。
后来进行key的Hex编码处理：
NSString *keyHex = [GMUtils stringToHex:pubKey];
然而，加密@"123456"的结果依然返回为nil。
请问还要处理什么吗？

**Comment by muzipiao** [comment]
后台提供给你的是 PEM 格式，将中间的字符串读出来，然后 base64 解码得到 NSData 格式数据，将 NSData 格式数据转为 16 进制字符串传入就可以了。

**Comment by Lshenshi** [comment]
我刚刚按照你说的试了。结果是我的pubKey的16进制字符串为4d466b774577...(中间忽略)....b413d3d
字符串长度为248。
你给的范例pubKey为0408E3FFF9505BCFAF9307E665E9229F4E1B3936437A870407EA3D97886BAFBC9C624537215DE9507BC0E2DD276CF74695C99DF42424F28E9004CDE4678F63D698
字符串长度为130。
依然失败了，是我的长度有问题，还是字符串只能有大写字母？

**Comment by Lshenshi** [comment]
应该是长度问题，我刚刚用大写的16进制字符串试了，为4D466B774577...(中间忽略)....6B413D3D
字符串长度还是为248。
依然失败了，是我的长度pubKey有问题。

**Comment by Lshenshi** [comment]
对了，还想请教一下，sm4是密钥长度和加密明文加密密文都为16个字节，但是范例里面的密钥和ivec都是32位，是因为都经过Hex 编码了吗？

**Comment by Lshenshi** [comment]
> 后台提供给你的是 PEM 格式，将中间的字符串读出来，然后 base64 解码得到 NSData 格式数据，将 NSData 格式数据转为 16 进制字符串传入就可以了。

我发现后台返回的pubkey长度为124字节，但是后台那边用ans1view检测之后说只有66字节长度，很奇怪，是获取有问题吗？

**Comment by Lshenshi** [comment]
> 后台提供给你的是 PEM 格式，将中间的字符串读出来，然后 base64 解码得到 NSData 格式数据，将 NSData 格式数据转为 16 进制字符串传入就可以了。
