### ISSUE TITLE
你好，请教关于证书读取出现的问题

### ISSUE THREAD

**Issue by Lshenshi** [muzipiao/GMObjC#47]
你好，多有打搅，请多见谅。
我读取.key文件的公钥，解析读取后，得到格式为
-----BEGIN PUBLIC KEY-----
MFkwEwYHK...(中间忽略)....QbJMgIT
PzAYl4qN...(中间忽略)....1JxIw+TXf/R9/jSkkkA==
-----END PUBLIC KEY-----
但是安卓读取.key文件的公钥得到：
EC Public Key [6c:37:39:4e:bd:...(中间忽略)....2:9b:3d:37:4d:5d:b0:93:db]
            X: 8f6432e54a5c...(中间忽略)....18978e2a34f873d1ad
            Y: 163f98a462fd...(中间忽略)....35dffd1f7f8d292490
我使用安卓的XY两字符串的公钥加04开头，完全没问题，所以应该是我读取.key文件有问题，所以我想请教应该怎么获取安卓这种格式的公钥，非常感谢。

**Comment by muzipiao** [comment]
猜测PEM格式公私钥进行了ASN1编码，Android应该是读取的时候进行了解码，iOS暂未实现。
你可以参考Android源码进行解密，或者参考openssl源码中`struct SM2_Ciphertext_st`密文的ASN1编码解码，自行实现。
GMObjC暂时未使用PEM格式，后期会加上，近几天出差，加上时间暂时不能确定。

**Comment by Lshenshi** [comment]
> 猜测 PEM 格式公私钥进行了ASN1编码，Android 应该是读取的时候进行了解码，iOS 暂未实现。
> 你可以参考 Android 源码思路实现 OC 的公私钥 ASN1 解码，或者参考 openssl 源码中`struct SM2_Ciphertext_st`，它是 SM2 密文的 ASN1 编码解码，参考它们尝试自行实现。
> GMObjC暂时未使用PEM格式，后期会加上，近几天出差，加上时间暂时不能确定。

非常感谢您的答复，我决定借助安卓已经解析好的公钥XY数据来处理国密了。
