### ISSUE TITLE
SM4加密后结果为null

### ISSUE THREAD

**Issue by xiaosheng-W** [muzipiao/GMObjC#48]
NSString *sm4Key = @"8888888888888888";
NSString *plaintext = @"{\"idserial\":\"123456\"}";
NSString *ecbCipertext = [GMSm4Utils ecbEncryptText:plaintext key:sm4Key];
NSLog(@"打印SM4加密:%@", ecbCipertext);

![image](https://user-images.githubusercontent.com/37129996/116640808-f3ca1980-a99d-11eb-9baa-dd45a8725727.png)

**Comment by muzipiao** [comment]
sm4Key 应为 32 字节长度16进制格式字符串，"8888888888888888" 非16进制格式，长度为16字节

**Comment by xiaosheng-W** [comment]
多谢回复
