### ISSUE TITLE
iOS使用secp256k1出现校验失败

### ISSUE THREAD

**Issue by peter-Kings** [muzipiao/GMObjC#49]
单独使用demo里的testECDH，出现校验失败，加密算法用的k256k1EllipticCurveType 
EC_GROUP *group = EC_GROUP_new_by_curve_name(k256k1EllipticCurveType); // 椭圆曲线

**Comment by peter-Kings** [comment]
设置变量static int k256k1EllipticCurveType = NID_secp256k1;

**Comment by muzipiao** [comment]
在 GMObjCDef.h 文件中有几种常用曲线的定义，使用前先调用API设置曲线即可
`[GMSm2Utils setEllipticCurveType:GMCurveType_secp256k1];`
