### ISSUE TITLE
关于sm2keyexchange

### ISSUE THREAD

**Issue by qqbzg** [muzipiao/GMObjC#50]
最近和java同学联调，关于密钥协商这块，我用的ecdh，但java端亮出了SM2keyExchange的神秘算法，说是jce自带的。
乍一看和ecdhe还有点像，这块儿求教@muzipiao，openssl也提供类似的接口吗？

**Comment by muzipiao** [comment]
不是有点像，就是同一个，ecdh密钥协商算法的不同语言实现，ecdh是算法。
SM2keyExchange是java端bouncycastle库中对 ECDH 算法的实现；
openssl实现在sm2_sign.c文件中；
bc库和openssl都是开源的，下载源码看一下。

**Comment by qqbzg** [comment]
我用的库里面封装好的ecdh，bc库里面有专门对应的算法是对应的ecdh（应该是最基础的一个类），但是里面的sm2keyexchange不太一样，他涉及的密钥是两对（我理解哈，一对static的密钥，一对ephemeral的密钥），然后我找了半天，只有一个ecdhe（注意，后面有个e似乎能对应上），就有点困惑了

**Comment by qqbzg** [comment]
我用的就是@muzipiao的库里面的封装好的ecdh算法，涉及到的相当于客户端，服务端各自是一对密钥。SM2keyExchange在java端涉及的是服务端两对密钥（static和emphemeral两对密钥），看了下源码，猜测是openssl里的       ECDH_compute_key(ecdh_text, outlen, pub_point, key, kdf) 这块算法相关。但是网上关于ECDH_compute_key的资源不多。在GMObjC中kdf这块应该是赋值了一个0，估计要想和java的SM2keyExchange匹配，是要传入一个对应的kdf？

头秃...

**Comment by JimAndLulu** [comment]
> 我用的就是@muzipiao的库里面的封装好的ecdh算法，涉及到的相当于客户端，服务端各自是一对密钥。
> 
> SM2keyExchange在java端涉及的是服务端两对密钥（static和emphemeral两对密钥），看了下源码，猜测是openssl里的 ECDH_compute_key(ecdh_text, outlen, pub_point, key, kdf) 这块算法相关。但是网上关于ECDH_compute_key的资源不多。
> 
> 在GMObjC中kdf这块应该是赋值了一个0，这个emphemeral key是跟kdf有关？还是密钥验证？
> 
> c这块，关于sm2的密钥协商我基本搜不到什么参考。奈何才疏，那些贼复杂的数学运算又是一头雾水。头秃
> 
> 头秃...

你好，请问你这个问题解决了吗？我们的服务器跟安卓都是java 使用SM2keyExchange交换密钥，ios不知道怎么解决呢

**Comment by bennyWang0806** [comment]
> > 我用的就是@muzipiao的库里面的封装好的ecdh算法，涉及到的相当于客户端，服务端各自是一对密钥。
> > SM2keyExchange在java端涉及的是服务端两对密钥（static和emphemeral两对密钥），看了下源码，猜测是openssl里的 ECDH_compute_key(ecdh_text, outlen, pub_point, key, kdf) 这块算法相关。但是网上关于ECDH_compute_key的资源不多。
> > 在GMObjC中kdf这块应该是赋值了一个0，这个emphemeral key是跟kdf有关？还是密钥验证？
> > c这块，关于sm2的密钥协商我基本搜不到什么参考。奈何才疏，那些贼复杂的数学运算又是一头雾水。头秃
> > 头秃...
> 
> 你好，请问你这个问题解决了吗？我们的服务器跟安卓都是java 使用SM2keyExchange交换密钥，ios不知道怎么解决呢

你好,请问这个问题解决了吗? ios 有实现方式吗?

**Comment by bennyWang0806** [comment]
你好 请问sm2秘钥协商支持类型java,  selfId, otherId,SM2keyExchange吗
