### ISSUE TITLE
pod集成后，项目运行失败，但是编译成功。报错：内存读取失败，如下图

### ISSUE THREAD

**Issue by hms040717007** [muzipiao/GMObjC#52]
<img width="1273" alt="截屏2021-07-07 10 51 52" src="https://user-images.githubusercontent.com/17900926/124698624-cf4d6900-df1b-11eb-9232-22324ba8fa29.png">

**Comment by muzipiao** [comment]
项目中可能存在低版本openssl，参考README文档，编译为动态库解决多版本兼容问题

**Comment by hms040717007** [comment]
> 项目中可能存在低版本openssl，参考README文档，编译为动态库解决多版本兼容问题

我的项目中也集成百度和高德地图，应该是百度或者高德地图中有加密和你的库的 OpenSSL 冲突
