### ISSUE TITLE
SM4支持PKCS5Padding

### ISSUE THREAD

**Issue by fzuycg** [muzipiao/GMObjC#54]
你好，请问SM4填充方式能支持PKCS5Padding吗？或者有一个参数可选。

**Comment by muzipiao** [comment]
我以前回答过一样的issue，PKCS5Padding 不适合 SM4 加密填充。
1. PKCS5填充长度为 1-8 字节，加密字符长度 len，填充长度 = 8 - len % 8；
2. PKCS7填充1-255字节都可以，如果需要填充k位(1<=k<=255)，则填充长度 = k - len % k；
3. 由于 SM4加密要求原始密文必须是 SM4_BLOCK_SIZE = 16 的倍数，所有选择PKCS7填充1-16；使用PKCS5填充是8的倍数，不满足是16的倍数，不适合SM4加密填充。

**Comment by fzuycg** [comment]
好的，感谢你的回答
