### ISSUE TITLE
导入GMObjC.framework到项目中报错

### ISSUE THREAD

**Issue by xiaofei730** [muzipiao/GMObjC#55]
编译的时候没有报错，运行的时候报错
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_GMSm2Utils", referenced from:
      objc-class-ref in FJNXLoginViewController.o
ld: symbol(s) not found for architecture armv7
clang_bk: error: linker command failed with exit code 1 (use -v to see invocation)
[$] waitpid = 41212 
[$] run clang_bk fail,not exist 
[$] nagain clang exit

**Comment by muzipiao** [comment]
GMObjC 默认不支持 armv7 & armv7s，如果需要，可以替换支持 armv7 的 openssl.framework(https://github.com/muzipiao/GMOpenSSL)，然后手动编译 GMObjC.framework 即可。

**Comment by xiaofei730** [comment]
好的，我试下

**Comment by xiaofei730** [comment]
现在项目可以编译和运行，不过测试的时候，加密结果为空，无法进行加密
-(void)testSM
{
    NSString *pubKey = @"0408E3FFF9505BCFAF9307E665E9229F4E1B3936437A870407EA3D97886BAFBC9"
                        "C624537215DE9507BC0E2DD276CF74695C99DF42424F28E9004CDE4678F63D698";
    // 私钥
    NSString *prikey = @"90F3A42B9FE24AB196305FD92EC82E647616C3A3694441FB3422E7838E24DEAE";

    // 明文
    NSString *plaintext = @"123456"; // 普通明文
    NSString *plainHex = @"313233343536"; // Hex 格式字明文（123456 的 Hex 编码为 313233343536）
    NSData *plainData = [NSData dataWithBytes:"123456" length:6]; // NSData 格式明文

    // sm2 加密
    NSString *enResult1 = [GMSm2Utils encryptText:plaintext publicKey:pubKey]; // 加密普通字符串
    NSString *enResult2 = [GMSm2Utils encryptHex:plainHex publicKey:pubKey]; // 加密 Hex 编码格式字符串
    NSData *enResult3 = [GMSm2Utils encryptData:plainData publicKey:pubKey]; // 加密 NSData 类型数据

    // sm2 解密
    NSString *deResult1 = [GMSm2Utils decryptToText:enResult1 privateKey:prikey]; // 解密为普通字符串明文
    NSString *deResult2 = [GMSm2Utils decryptToHex:enResult2 privateKey:prikey]; // 解密为 Hex 格式明文
    NSData *deResult3 = [GMSm2Utils decryptToData:enResult3 privateKey:prikey]; // 解密为 NSData 格式明文
}
运行上述这段代码，加密结果和解密结果都为空

**Comment by xiaofei730** [comment]
将GMObjC文件夹和openssl2.2.0手动拖入项目中

**Comment by xiaofei730** [comment]
修改项目配置VALID_ARCHS值，替换openssl2.2.0，打出framework包，就可以了
