### ISSUE TITLE
question

### ISSUE THREAD

**Issue by BingleiM** [muzipiao/GMObjC#6]
谢谢

**Comment by muzipiao** [comment]
1. 首先 C2 是密文长度，长度和原文长度相等，原文32字节，则C2长度32字节（16 进制编码后 64 字节），所以 C2 是没办法固定的；
2. C1 长度是椭圆曲线上的一个随机点，每个点是 BigNum 类型，BigNum 转 16 进制编码为 64 字节，所以 C1 长度（16进制编码方式）固定为 128 字节，16进制解码后就变为 64 字节了。
3. C3 是 Hash 值，固定长度 32 字节，转 Hex 编码（16 进制）后为固定 64 字节。

**Comment by BingleiM** [comment]
你好, 使用 Demo 进行 SM2 加密时, 传入密文长度是 192 字节, 输入密文长度应该是 192 + 32 + 64 = 288，转 Hex 编码后应该是 576 字节, 然而目前接口输出的是 406 字节, 
断点发现 
`
size_t ctext_len = 0;  // 函数计算得出的 ctext_len = 203
        if (!sm2_ciphertext_size(key, digest, msg_len, &ctext_len)) {
            break;
        }
`
期待你的回复, 谢谢

**Comment by muzipiao** [comment]
注意中英文，全角半角符号，UTF-8格式和gbk格式汉字占两个字符，UTF-16占4字节，所以iOS字符串长度不是字节数，是字符个数lifei-------- 原始邮件 --------发件人： BingleiM <notifications@github.com>日期： 2020年1月14日周二 14:59收件人： muzipiao/GMObjC <GMObjC@noreply.github.com>抄送： CocoaFei <676288949@qq.com>, Comment <comment@noreply.github.com>主    题： Re: [muzipiao/GMObjC] question (#6)你好, 使用 Demo 进行 SM2 加密时, 传入密文长度是 192 字节, 输入密文长度应该是 192 + 32 + 64 = 288，转 Hex 编码后应该是 576 字节, 然而目前接口输出的是 406 字节,

断点发现

size_t ctext_len = 0;  // 函数计算得出的 ctext_len = 203 if (!sm2_ciphertext_size(key, digest, msg_len, &ctext_len)) { break; }

期待你的回复, 谢谢
