### ISSUE TITLE
加密数据量过大会崩溃

### ISSUE THREAD

**Issue by yuxuan777** [muzipiao/GMObjC#61]
非常感谢作者的辛勤付出，提供了很棒的加密工具，解决了我们的问题。
但是目前我们发现当数据量过大，比如有图片base64字符串进行SM4加密时，会发生crash，目前定位到应该是在源码中的uint8_t p_text[result_len]; 这一行，由于数据过长数组过大造成栈溢出了。我尝试改为malloc之后可以解决。

请问大佬是否有进一步优化的可能？

**Comment by muzipiao** [comment]
下载最新版本，在上个版本已修复

**Comment by yuxuan777** [comment]
看到了，感谢大佬回复~
