### ISSUE TITLE
貌似有更好的C语言依赖GmSSL和其v3版本

### ISSUE THREAD

**Issue by FunnyerFeng** [muzipiao/GMObjC#63]
https://github.com/guanzhi/GmSSL
https://github.com/guanzhi/gmssl-v3-dev

**Comment by muzipiao** [comment]
1. 项目是开源的，可自行修改，只需依赖支持 armv7 版本 OpenSSL 即可；
2. OpenSSL 和 GMSSL 都是 C 版本，GMObjC 是基于 OpenSSL 进行 OC 封装，定位不同。
