### ISSUE TITLE
SM4加解密

### ISSUE THREAD

**Issue by destinyxxl** [muzipiao/GMObjC#65]
无法和服务端java实现的SM4实现互通加解密，求指导

后端给的加密过的密文(base64加密)：NE4l3DNdrJEy3vO78kyec6dPXQfqf8rOfpu8v0wW8ZVBstysumoWKFW9KSadXn8lSYiX3gYxPK0bcBycldBueOU3jU8cYTs2ArYbgR15/N36PMQwGF23gvTu0zgVlT6gywZgaLeVDsv3IlmuX50zytidccjMaL6J+QJQ7+03ufUZw3QxrQ8hl4B8uP930ayjT0dQiBlg+XLo87NKzuz76Vph8O5Hc5N3xJL/P7b/eF0=

key：0ccd81e9bfda47cf801d289c1ac56f92

![截屏2022-06-09 下午3 09 28](https://user-images.githubusercontent.com/13796652/172786685-ecae63a0-8129-414f-bc06-b46ffc4c537f.png)

**Comment by muzipiao** [comment]
与后端确认 Padding 规则，GMSm4Utils 使用最常用的 PKCS7Padding，如果确认 Padding 一致后还不能解密，把原文贴出来，也可以利用在线工具排除原因，[在线 SM4 网站 https://aks.jd.com/tools/sec/](https://aks.jd.com/tools/sec/)

**Comment by destinyxxl** [comment]
感谢回复~
我用您上面贴的在线网站发现无法解密服务端的密文，而GMSm4Utils生成的可以通过网站校验，不知道为什么。。。我现在让服务端找一个可以通过网站加解密的Java实现再联调。

1. 服务端这两天又更换了一套java实现(附件)，现在提供的秘钥是16位的 不知道GMSm4Utils是否支持
2. 我看了他们的实现代码，是基于PKCS7Padding设置的padding

麻烦有时间帮忙看看 多谢

密文：F0MEz8mf+aoLsdD4fcgHjBzGljTRm/k4j5PXFQMlFsW0qMB0R6YI0JD2lzZaB7UQU9osZ7YQk/xVVfemo9He7Qm7ZBgrUvksSOuo3M71dTtsGhRC7H7ETh+Ob+2MDJTzrtJ5ITlC77zl0jY80BgiWgAxJGol+gH348Ctbi5eJKOH2OU5OddhHY5Aqiog4jc5BW2bktLAK0IFG6u+DbtGVeQYWiFYldRGDPpcpTr3XWArFKrT8r5ACHSNbfLCsqIHWWhRGGPOTzst9NILCGYVufweLOzP4Dl9pcqQ5l7cS88=

秘钥：d8f37edaf21f437

![image](https://user-images.githubusercontent.com/13796652/173326008-cce91088-c5a2-46b0-84d2-212ad5bb947c.png)

[Java.zip](https://github.com/muzipiao/GMObjC/files/8889755/Java.zip)
3

**Comment by muzipiao** [comment]
这 java 代码，它自己加密解密都走不通，让别人怎么解...
看了一眼，java 代码应该是 copy 的开源库，但改的不对，找一份正确的开源库即可。

**Comment by destinyxxl** [comment]
> 这 java 代码，它自己加密解密都走不通，让别人怎么解... 看了一眼，java 代码应该是 copy 的开源库，但改的不对，找一份正确的开源库即可。

他们用代码自己可以正常加解密，原来是周伯通自己能跟自己打  哈哈哈~

**Comment by destinyxxl** [comment]
> > 这 java 代码，它自己加密解密都走不通，让别人怎么解... 看了一眼，java 代码应该是 copy 的开源库，但改的不对，找一份正确的开源库即可。
> 
> 他们用代码自己可以正常加解密，原来是周伯通只能跟自己打 哈哈哈~

服务端找了一个可以通过网站校验的，现在已经互通没问题了 多谢作者
