### ISSUE TITLE
java加密的数据解不出来

### ISSUE THREAD

**Issue by BigDad3** [muzipiao/GMObjC#68]
大佬你好：

私钥：MIGTAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBHkwdwIBAQQgwAiExBi5nLzMynDVGdhnFU0ONgeREPeJsNm7iH7Rk2+gCgYIKoEcz1UBgi2hRANCAAQ9YSqlMRDWGPIdjzMFmzNVv5H8mheudueWusn0CBaURyi0QyXOgqk7mo9wnTayb1SxaFi0yzFhlak3kEtCf4jK
 
加密数据：BGDG3Ejl93WTO7Iv8AgYY+REzlHuVhEJW7TEhmJ8FrywWIQM+8USbVAKTulS3hysPl+JVgcvBAnL+z7kzkbP8ajw+sqptGznTuIavvclrTEhT44/uKNCcF3L/4lS3fxzf8YTaf85F42y
这是java生成的私钥以及加密数据

我的代码是这样的：
```
 -(void)testASN1{
    NSString *priKey = @"MIGTAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBHkwdwIBAQQgwAiExBi5nLzMynDVGdhnFU0ONgeREPeJsNm7iH7Rk2+gCgYIKoEcz1UBgi2hRANCAAQ9YSqlMRDWGPIdjzMFmzNVv5H8mheudueWusn0CBaURyi0QyXOgqk7mo9wnTayb1SxaFi0yzFhlak3kEtCf4jK";
    NSData *priKeyData = [GMUtils base64Decode:priKey];
    NSString *priKeyHex = [GMUtils dataToHex:priKeyData];
  
    NSString *enStr = @"BGDG3Ejl93WTO7Iv8AgYY+REzlHuVhEJW7TEhmJ8FrywWIQM+8USbVAKTulS3hysPl+JVgcvBAnL+z7kzkbP8ajw+sqptGznTuIavvclrTEhT44/uKNCcF3L/4lS3fxzf8YTaf85F42y";
    NSData *enStrData = [GMUtils base64Decode:enStr];
    NSString *enStrHex = [GMUtils dataToHex:enStrData];
    
    NSString *c1c3c2 = [GMSm2Utils convertC1C2C3ToC1C3C2:enStrHex hasPrefix:NO];
    NSString *asn1Result = [GMSm2Utils asn1EncodeWithC1C3C2:c1c3c2];

    NSString *deResult1 = [GMSm2Utils decryptToText:asn1Result privateKey:priKeyHex]; // 解密为普通字符串明文
    
    NSLog(@"========== GW deResult1:%@", deResult1);
} 
```

解密出来为空，不知道大佬是否有时间帮忙定位下是什么问题。

**Comment by muzipiao** [comment]
这私钥明显过长，辨认是 PEM 格式，下策使用 GMSm2Bio 读取私钥，上策与后端协商返回 HEX 格式密钥，另外 java 端加解密一般用的 BouncyCastle，密文有 04 前缀。
```
-(void)testASN1{
    NSString *priKey = @"MIGTAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBH"
    "kwdwIBAQQgwAiExBi5nLzMynDVGdhnFU0ONgeREPeJsNm7iH7Rk2+gCgYI"
    "KoEcz1UBgi2hRANCAAQ9YSqlMRDWGPIdjzMFmzNVv5H8mheudueWusn0CB"
    "aURyi0QyXOgqk7mo9wnTayb1SxaFi0yzFhlak3kEtCf4jK";
    NSArray *pemList = @[@"-----BEGIN EC PRIVATE KEY-----", priKey,
                         @"-----END EC PRIVATE KEY-----"];
    NSString *pemPriKey = [pemList componentsJoinedByString:@"\n"];
    NSString *priKeyHex = [GMSm2Bio readPrivateKeyFromPemString:pemPriKey];
    
    NSString *enStr = @"BGDG3Ejl93WTO7Iv8AgYY+REzlHuVhEJW7TEhmJ8"
    "FrywWIQM+8USbVAKTulS3hysPl+JVgcvBAnL+z7kzkbP8ajw+sqptGznTuI"
    "avvclrTEhT44/uKNCcF3L/4lS3fxzf8YTaf85F42y";
    NSData *enStrData = [GMUtils base64Decode:enStr];
    NSString *enStrHex = [GMUtils dataToHex:enStrData];
    
    NSString *c1c3c2 = [GMSm2Utils convertC1C2C3ToC1C3C2:enStrHex hasPrefix:YES];
    NSString *asn1Result = [GMSm2Utils asn1EncodeWithC1C3C2:c1c3c2];
    NSString *deResult1 = [GMSm2Utils decryptToText:asn1Result privateKey:priKeyHex];
    
    NSLog(@"========== GW deResult1:%@", deResult1);
}
```

**Comment by BigDad3** [comment]
> 这私钥明显过长，辨认是 PEM 格式，下策使用 GMSm2Bio 读取私钥，上策与后端协商返回 HEX 格式密钥，另外 java 端加解密一般用的 BouncyCastle，密文有 04 前缀。
> 
> ```
> -(void)testASN1{
>     NSString *priKey = @"MIGTAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBH"
>     "kwdwIBAQQgwAiExBi5nLzMynDVGdhnFU0ONgeREPeJsNm7iH7Rk2+gCgYI"
>     "KoEcz1UBgi2hRANCAAQ9YSqlMRDWGPIdjzMFmzNVv5H8mheudueWusn0CB"
>     "aURyi0QyXOgqk7mo9wnTayb1SxaFi0yzFhlak3kEtCf4jK";
>     NSArray *pemList = @[@"-----BEGIN EC PRIVATE KEY-----", priKey,
>                          @"-----END EC PRIVATE KEY-----"];
>     NSString *pemPriKey = [pemList componentsJoinedByString:@"\n"];
>     NSString *priKeyHex = [GMSm2Bio readPrivateKeyFromPemString:pemPriKey];
>     
>     NSString *enStr = @"BGDG3Ejl93WTO7Iv8AgYY+REzlHuVhEJW7TEhmJ8"
>     "FrywWIQM+8USbVAKTulS3hysPl+JVgcvBAnL+z7kzkbP8ajw+sqptGznTuI"
>     "avvclrTEhT44/uKNCcF3L/4lS3fxzf8YTaf85F42y";
>     NSData *enStrData = [GMUtils base64Decode:enStr];
>     NSString *enStrHex = [GMUtils dataToHex:enStrData];
>     
>     NSString *c1c3c2 = [GMSm2Utils convertC1C2C3ToC1C3C2:enStrHex hasPrefix:YES];
>     NSString *asn1Result = [GMSm2Utils asn1EncodeWithC1C3C2:c1c3c2];
>     NSString *deResult1 = [GMSm2Utils decryptToText:asn1Result privateKey:priKeyHex];
>     
>     NSLog(@"========== GW deResult1:%@", deResult1);
> }
> ```

这个代码是好使的，多谢大佬解答。
