### ISSUE TITLE
SM2加密，同样的明文，多次加密密文长度不一样 

### ISSUE THREAD

**Issue by winAilotus** [muzipiao/GMObjC#7]
SM2加密，同样的明文，多次加密密文长度不一样，本地加解密没问题，但是传递给后端(Java)就解不出来了 。

**Comment by muzipiao** [comment]
1. 密文不一样是因为密文是 OpenSSL 加密默认 ASN1 编码格式，后端需保持一致；
2. 与后端调试前，你需要和后端确认后端密文格式是 ASN1 编码格式，还是未进行 ASN1 编码的普通 C1C3C2 或 C1C2C3 排序格式密文；
3. 如果后端是 C1C3C2 普通格式，iOS 端按照对应格式解码为对应格式，传给后端即可。

**Comment by winAilotus** [comment]
目前后端是C1C3C2 ASN1 编码格式，前端也是采用的同样的方式。因为同样的明文每次加密位数不一样，后台有时候可以解出来，有时候解不出来，解不出来的时候后台会报：java.lang.IllegalArgumentException: Invalid point coordinates。

**Comment by muzipiao** [comment]
原因猜测：从报错信息猜测是随机坐标点 C1 校验失败。C1 的坐标 x, y 都是 BIGNUM 类型，一般情况下 x, y 转换为 16 进制编码格式长度都为 64 字节长度，但个别情况（约千分之三），获取随机坐标点长度不足，转 16 进制编码后长度 < 64 字节（例如 62 字节），这时如果后端是按照固定长度 64 截取 C1 的 x 与 y 的，校验就会失败。

解决方案：
1. 客户端的 ASN1 编码是 OpenSSL 固定实现的，暂时无法更改；如果想更改，则需要重写它 ASN1 实现方法。所以后端能兼容最好，检查一下是否是按照固定长度截取的。
2. 另外一种方案是传未 ASN1 编码的 C1C3C2，客户端和 java 后端有对应 API 可解密。
