### ISSUE TITLE
支持SM2算法进行密钥交换吗？

### ISSUE THREAD

**Issue by JimAndLulu** [muzipiao/GMObjC#71]
您好！请问该库支持SM2算法进行密钥协商吗？我看项目目前只支持ECDH密钥协商，我们项目需要SM2算法进行密钥协商，请告诉我该如何实现，万分感谢🙏！

**Comment by muzipiao** [comment]
你现在的状态应该是还没理解什么是密钥协商，先 Google 理解，加解密本来就是抽象的，需要先自己理解；
* 项目中有官方文档【国密官方文档】，仔细看 Readme 文档中有 ECDH 描述；
* 密钥协商的大白话就是双方使用公开的信息（如公钥/随机值），双方通过网络交换这个公开信息，各自使用私钥和这个公开信息进行计算，计算得到的值就是协商的密钥（密钥协商的特点就是双方计算的这个值一样），协商的过程就是密钥协商，项目中的 ECDH 能满足大部分需求。

**Comment by JimAndLulu** [comment]
> 你现在的状态应该是还没理解什么是密钥协商，先 Google 理解，加解密本来就是抽象的，需要先自己理解；
> 
> * 项目中有官方文档【国密官方文档】，仔细看 Readme 文档中有 ECDH 描述；
> * 密钥协商的大白话就是双方使用公开的信息（如公钥/随机值），双方通过网络交换这个公开信息，各自使用私钥和这个公开信息进行计算，计算得到的值就是协商的密钥（密钥协商的特点就是双方计算的这个值一样），协商的过程就是密钥协商，项目中的 ECDH 能满足大部分需求。

感谢您的回复，因为我们项目之前的密钥协商用的是ECDH，现在安卓跟服务端都换成了SM2KeyExchangePrivateParameters，ios卡住了，要实现跟安卓和服务器交换密钥，请问您可以提供一下思路吗
