### ISSUE TITLE
请问sm2加密(C1C3C2) 后端有时候会偶尔出现解密失败的问题 这种问题有遇到过吗

### ISSUE THREAD

**Issue by xdy1672** [muzipiao/GMObjC#73]

**Comment by muzipiao** [comment]
未见他人反馈，在用业务也正常运行，与 BouncyCastle 库做过单元测试，批量加解密正常。

**猜测，偶尔失败可能是由于后端密钥转码未补齐。**

椭圆曲线的私钥是一个大整数，公钥是一个点坐标。公钥 (Gx, Gy) 和私钥 d 转 Hex 格式时，Gx, Gy, d 都是 BIGNUM 类型，逐个转 Hex 一般为 64 字符，不足 64 字符的情况下需要在前面补0（Java端可参考 bouncycastle 库源码密钥转码补齐规则），这样公钥长度为 128 字符，私钥 64 字符。

公钥一般使用非压缩格式，前面有 04 代表非压缩格式，即 公钥=04GxGy，所以可能是后端采用了压缩格式或转码错误。

**Comment by xdy1672** [comment]
公钥是后端给的压缩格式的128字符， iOS 这边去sm2加密时还要在公钥前加上04, ，加密后把ASN1格式的密文解码成C1C3C2密文给后端。确实是一个很奇怪的问题只会偶尔出现。解密失败的情况拿着私钥和密文在这个 https://the-x.cn/cryptography/Sm2.aspx 上面去解密也失败。

**Comment by muzipiao** [comment]
SM2加解密的代码银行现在还在用，出问题概率不大，估计是后端给的私钥或者密文有问题
