### ISSUE TITLE
密钥

### ISSUE THREAD

**Issue by VictorZHV** [muzipiao/GMObjC#77]
请问SM4的密钥，服务端提供的是56位格式的字符串，也不是16进制的，该怎么处理？
<img width="413" alt="image" src="https://user-images.githubusercontent.com/17470755/220334543-b72a9a38-67ba-4b97-b531-f15e7ed1ff06.png">

**Comment by muzipiao** [comment]
这是 Base64 编码的，与服务端协商一致，他是怎么编码的，客户端反过来操作，获取密钥数据即可。
