### ISSUE TITLE
手动引入的时候，找不到sm2.h,sm3.h,sm4.h中的方法

### ISSUE THREAD

**Issue by chaichaiquan** [muzipiao/GMObjC#8]
因为某些原因，只能手动引入，不能使用cocopods。
我需要将您的GMObjC以及GMOppenSSL手动引入，并封装在我自己的SDK内， 手动引入后，编译打包成framework库没有问题，但是项目中引入这个framework库后，报找不到sm2.h,sm3.h,sm4.h中的方法。
路径配置都看了，是没有问题的。能帮忙看下是什么问题吗？
<img width="691" alt="截屏2020-02-11下午1 24 17" src="https://user-images.githubusercontent.com/14212428/74213077-7d76c400-4cd2-11ea-9548-869d5d1a459d.png">

**Comment by muzipiao** [comment]
这是找不到对应 .c 文件报的错，说明你自己封装的 framework 并没有真正导入 OpenSSL.framework ，只是头文件引用而已，二次封装 framework 方法不对。
GMObjC 代码量不大，你可以自由封装为 .a 或 framework。 GMOpenSSL 是 OpenSSL.framework 上传 cocoapods 后的别名而已，不用再次封装，直接把 OpenSSL.framework 作为单独的组件，拖入主工程集成即可。

**Comment by MYStrict** [comment]
你好，我直接把 OpenSSL.framework 作为单独的组件导入后，在测试demo中可以使用，但是放到自己项目中的时候，加密结果返回nil，不知道是什么原因啊
