### ISSUE TITLE
读取 .cer 后缀的证书为nil

### ISSUE THREAD

**Issue by zmh10241015** [muzipiao/GMObjC#80]
你好！请教个问题，就是我直接读取后台给的 .cer 数字证书的公钥是nil。java那边是可以正常读取的。

**Comment by zmh10241015** [comment]
把cer证书转成X509 结构体，然后通过openssl X509_get0_pubkey_bitstr 拿到公钥。可以实现

**Comment by muzipiao** [comment]
GMSm2Bio 目前未兼容 X509 编码格式的证书，仅支持 PEM/DER 格式公私钥。
