### ISSUE TITLE
mac app支持

### ISSUE THREAD

**Issue by iPermanent** [muzipiao/GMObjC#84]
这个库是纯算法的代码，不涉及到UI的功能，能否考虑发个版本，在podspec里加入mac的支持呢

**Comment by muzipiao** [comment]
已经支持了，项目有一个 GMV4 分支，支持 Mac；
主体已经完成，细节目前没时间完善，但不影响使用；
你可以拉下来拖入项目直接用，有问题联系我。

**Comment by iPermanent** [comment]
好的  感谢，我使用podfile branch的方式来引用吧
