### ISSUE TITLE
SM2 秘钥协商问题

### ISSUE THREAD

**Issue by bennyWang0806** [muzipiao/GMObjC#86]
/**
     * @param initiator         true表示发起方，false表示响应方
     * @param keyBits           生成的密钥长度
     * @param confirmationTag   确认信息，如果是响应方可以为null；如果是发起方则应为响应方的s1
     * @param selfStaticPriv    己方固定私钥
     * @param selfEphemeralPriv 己方临时私钥
     * @param selfId            己方ID
     * @param otherStaticPub    对方固定公钥
     * @param otherEphemeralPub 对方临时公钥
     * @param otherId           对方ID
     * @return
     */
    public static ExchangeResult calculateKeyWithConfirmation(boolean initiator, int keyBits, byte[] confirmationTag,
                                                              ECPrivateKeyParameters selfStaticPriv, ECPrivateKeyParameters selfEphemeralPriv, byte[] selfId,
                                                              ECPublicKeyParameters otherStaticPub, ECPublicKeyParameters otherEphemeralPub, byte[] otherId) {

大佬, 你好, Java 和Android 都是基于 org.bouncycastle 库函数调用, 

我看iOS  并没有上面的selfId 和 otherId  参数
///MARK: - ECDH 密钥协商
/// 椭圆曲线 Diffie-Hellman 密钥协商（ECDH），返回 64 字节 16 进制编码格式密钥
/// @param publicKey 临时公钥（其他端传入的公钥）
/// @param privateKey 临时私钥（当前端生成的私钥）
+ (nullable NSString *)computeECDH:(NSString *)publicKey privateKey:(NSString *)privateKey

求解,  谢谢

**Comment by muzipiao** [comment]
目前还没研究 OpenSSL 怎么加入标识 ID；
密钥交换协议中加入对方的标识 ID 应该是为了防范中间人攻击，双方都传空试试能不能用。
