### ISSUE TITLE
苹果新政 privacy manifest

### ISSUE THREAD

**Issue by NicolasKim** [muzipiao/GMObjC#89]
您好 
最近苹果要求提供三方SDK的manifest文件，经过扫描发现国秘SDK中使用了st_flags/st_size/fstat/lstat等函数，需要在manifest中说明。希望尽早支持。
🙏🙏

https://developer.apple.com/news/?id=3d8a9yyh

**Comment by FanningHau** [comment]
附议 [https://github.com/krzyzanowskim/OpenSSL/pull/195](url)

**Comment by lilin87788** [comment]
同求

**Comment by FunnyerFeng** [comment]
同求

**Comment by muzipiao** [comment]
GMObjC 无特殊 API 引用，依赖的 GMOpenSSL 库(即 openssl.xcframework)，已重新编译并增加 xcprivacy 文件。
1. pod 集成用户，执行`pod update`更新 GMOpenSSL 至 3.0.4 版本即可；
2. Carthage集成用户，按照 Readme 文档重新编译；
3. 手动及其他方式集成用户，手动替换。
