### ISSUE TITLE
 pod  fail

### ISSUE THREAD

**Issue by 411051493** [muzipiao/GMObjC#9]
pod search GMObjC
[!] Unable to find a pod with name, author, summary, or description matching `GMObjC`

 pod install
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "GMObjC":
  In Podfile:
    GMObjC (= 3.0.0)

None of your spec sources contain a spec satisfying the dependency: `GMObjC (= 3.0.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by muzipiao** [comment]
原因：这是 cocoapods 原因，无论你使用的是 CDN 还是 GitHub 上面的源，都有大概率失败；
示例：
1. 例如使用 CDN 时，源地址为 raw.githubusercontent.com，在你电脑终端使用`ping ping raw.githubusercontent.com`会看到丢包率很严重，这就是你 pod 安装失败的原因；
2. 你在安装时加入 verbose 参数，查看详细源地址，然后通过 ping 指令验证丢包率，eg：`pod update --verbose`，得到网址 xxx.xxxx.com 后 `ping xxx.xxxx.com` 查看丢包率。
解决办法：推荐手动集成 GMObjC 和 GMOpenSSL，次级方案切换网络，例如使用联通宽带或 4G 试试。
