### ISSUE TITLE
在 Swift PM 中直接添加该库报错

### ISSUE THREAD

**Issue by GrsisFee** [muzipiao/GMObjC#93]
在 Swift PM 中直接添加该库报错，报错信息如下：
<img width="1082" alt="image" src="https://github.com/muzipiao/GMObjC/assets/17040266/99d858ac-5883-465d-94de-5eb9ee1cecc7">
将代码下载到本地，在  SPM 中添加本地库可以成功。

**Comment by GrsisFee** [comment]
我用本地的 GitLab 试过了，还是不行。但按照网上提供的方法，把这个中文名的文件夹 及其 文件都删除后，可以了。
<img width="253" alt="image" src="https://github.com/muzipiao/GMObjC/assets/17040266/07a8f61e-28a7-41f3-aeb9-e5f7df7ef960">

**Comment by muzipiao** [comment]
那就有点奇怪了，SPM 库及其设置，只与 Package.swift 和2个文件夹相关，其他都可以删除。
1. Package.swift
2. XCFrameworks
3. GMObjC

**Comment by GrsisFee** [comment]
我也是看到这个文章，抱着试试的心态
https://blog.csdn.net/liangjiongxing/article/details/103601979

结果就可以了。。。。。。

**Comment by muzipiao** [comment]
这挺让人无语的，放 Package.swift 的目录不能有任何中文！可能是 SPM 的 Bug。

**Comment by GrsisFee** [comment]
也可能是  XCode BUG
