### ISSUE TITLE
openssl版本冲突问题

### ISSUE THREAD

**Issue by shengxiaolei** [muzipiao/GMObjC#99]
项目中有老旧的自封装的openssl需要集成用到GMObjC中的openssl相关文件请教下这个应该怎么做呢？

**Comment by muzipiao** [comment]
根据 Readme文档中，将 GMObjC 编译为 xcframework 动态库，不再需要嵌入 OpenSSL.xcframework，可解决多版本 OpenSSL 冲突问题。

**Comment by shengxiaolei** [comment]
现在是项目中有openssl低于1.1.1版本的，这样操作后国密算法无法实现了

请问有什么解决方案吗

**Comment by muzipiao** [comment]
上面的就是解决方案，项目里面使用的 openssl<1.1.1，GMObjC.xcframework 内部使用的是高版本的 openssl，他们互不影响，你调用的是 GMObjC，不是 openssl，也不需要在外部调用 openssl

**Comment by shengxiaolei** [comment]
请教一下 用到DBChainSm2也是要将DBChainSm2搞成动态库吗
